### PR TITLE
Make CORE:: fully available at compile time.

### PR DESCRIPTION
**Pull request by vrurg**
Fix for rakudo/rakudo#3058

### CODE REVIEW

**Comment by lizmat** [comment]
This PR seems to fix the original issue, but introduces a new one:

    $ perl6 --ll-exception -MOO::Monitors -e 'monitor A { our constant &foo = CORE::<&abs> }'
    Type check failed in binding; expected Callable but got Nil (Nil)
       at SETTING::src/core/Exception.pm6:62  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:throw)
     from SETTING::src/core/Exception.pm6:2768  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
     from src/vm/moar/Perl6/Ops.nqp:148  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Ops.moarvm:bind_error)
     from site#sources/D26BE9BE3E2E4446371F551DF52DDF70968D9CA0 (OO::Monitors):62  (/Users/liz/.perl6/precomp/CDAE4315055DEF05CC511722C030EE51455BEA8F/D2/D26BE9BE3E2E4446371F551DF52DDF70968D9CA0:compose)
     from src/Perl6/World.nqp:3322  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/World.moarvm:)
     from src/Perl6/World.nqp:5419  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/World.moarvm:)
     from src/Perl6/World.nqp:5427  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/World.moarvm:ex-handle)
     from src/Perl6/World.nqp:3321  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/World.moarvm:pkg_compose)
     from gen/moar/Perl6-Actions.nqp:3245  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Actions.moarvm:package_def)
     from gen/moar/stage2/QRegex.nqp:1602  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QRegex.moarvm:!reduce)
     from gen/moar/stage2/QRegex.nqp:1545  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QRegex.moarvm:!cursor_pass)
     from gen/moar/Perl6-Grammar.nqp:2174  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:package_def)
     from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/World.moarvm:!!LATENAME!!$meth_name)
     from gen/moar/stage2/QRegex.nqp:1644  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QRegex.moarvm:!protoregex)
     from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:package_declarator)
     from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:term:sym<package_declarator>)
     from gen/moar/stage2/QRegex.nqp:1644  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QRegex.moarvm:!protoregex)
     from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:term)
     from gen/moar/Perl6-Grammar.nqp:3639  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:termish)
     from gen/moar/stage2/NQPHLL.nqp:1131  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
     from gen/moar/Perl6-Grammar.nqp:3675  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:EXPR)
     from gen/moar/Perl6-Grammar.nqp:956  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:statement)
     from gen/moar/Perl6-Grammar.nqp:884  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:statementlist)
     from gen/moar/stage2/NQPHLL.nqp:1353  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:LANG)
     from gen/moar/Perl6-Grammar.nqp:1320  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:FOREIGN_LANG)
     from gen/moar/Perl6-Grammar.nqp:832  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:comp_unit)
     from gen/moar/Perl6-Grammar.nqp:555  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Grammar.moarvm:TOP)
     from gen/moar/stage2/QRegex.nqp:2211  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QRegex.moarvm:parse)
     from gen/moar/stage2/NQPHLL.nqp:2181  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:parse)
     from gen/moar/stage2/NQPHLL.nqp:2101  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
     from gen/moar/stage2/NQPHLL.nqp:2134  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:run)
     from gen/moar/stage2/NQPHLL.nqp:2126  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:)
     from gen/moar/stage2/NQPHLL.nqp:2121  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:compile)
     from gen/moar/stage2/NQPHLL.nqp:1805  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:eval)
     from gen/moar/stage2/NQPHLL.nqp:1944  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:)
     from gen/moar/stage2/NQPHLL.nqp:1999  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
     from src/Perl6/Compiler.nqp:52  (/Users/liz/Github/rakudo.moar/install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
     from gen/moar/stage2/NQPHLL.nqp:1924  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:command_line)
     from gen/moar/main.nqp:82  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:MAIN)
     from gen/moar/main.nqp:47  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<mainline>)
     from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<main>)
     from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<entry>)

**Comment by vrurg** [comment]
I know, it's not finalized yet. I have final fixes locally but they need additional tests in `roast`.

**Comment by jnthn** [comment]
@lizmat I'm curious: is the `monitor` significant in that example, or does it do the same with `class`?

**Comment by vrurg** [comment]
> @lizmat I'm curious: is the `monitor` significant in that example, or does it do the same with `class`?

It would be the same. The problem is that because of the changed schema of `CORE` loading wrong context is being located.

**Comment by vrurg** [comment]
@jnthn I must correct myself: it's only `monitor`-related issue. `class` is not affected!

**Comment by vrurg** [comment]
@lizmat `monitor` is ok now too. If travis won't mind, I'm gonna merge it.

**Pull request merged**
