### PR TITLE
Sort the binaries by version

### PR DESCRIPTION
**Pull request by jonathanstowe**
Assuming we always want to have the latest version of a binary
unless it has been otherwise specified then this seems to be
the simplest way to achieve that.

### CODE REVIEW

**Comment by lizmat** [comment]
perhaps .tail instead of [*-1] ??  :-)

**Comment by niner** [comment]
This will improve newly installed scripts but won't help for those which are already there. If instead we sort in the "files" method, it'd apply immediately to all installed scripts. And as right now there is no defined sort order to files' results, it shouldn't hurt to fit it to the scripts' use case.

**Comment by jonathanstowe** [comment]
Yes sorting in .files would be better, I didn't want to do that as I don't know where else it us used.

**Comment by niner** [comment]
Nothing in rakudo uses this method and as I said, the order is currently undefined anyway.

**Comment by jonathanstowe** [comment]
Hmm, though on reflection it seems to me that sorting in .files won't entirely fix it as they may appear in more than one Repository (though I don't know how often that will happen in practice.)

**Comment by niner** [comment]
Oh, that's true. Ok, this code needs some major refactor anyway because let's face it. It's not pretty :)

**Comment by jonathanstowe** [comment]
All good, I may revisit by moving the "find me the binaries" into a method in the CUR at some point :)

**Pull request closed without merging**
