### PR TITLE
Disallow creating Uni with out-of-range codepoints

### PR DESCRIPTION
**Pull request by moon-chilled**

### CODE REVIEW

**Comment by lizmat** [comment]
Thank you for this!  Two questions / requests:

- are we checking for negative values as well?
- instead of nqp::die, please create a named exception class with the necessary information as attributes, and do a `.new.throw` on that.

**Comment by moon-chilled** [comment]
Done!  Also added a check for surrogate codepoints.

I wonder if there's a way to make [this](https://github.com/MoarVM/MoarVM/blob/master/src/strings/utf8.c#L639) moarvm routine throw this exception?

**Comment by moon-chilled** [comment]
Oh huh, I guess that absent an isgt_u, the array[uint32] candidate needs a <0 check too.

**Comment by lizmat** [comment]
I don't think this is ready to be merged, right?

**Comment by moon-chilled** [comment]
I think I addressed all the feedback.  Did I miss anything?

**Comment by lizmat** [comment]
Thanks!

**Pull request merged**
