### PR TITLE
Keep .perl/.gist consistency among Set/Mix/Bag

### LINKED ISSUE #1958: Set.perl inconsistent with Bag/Mix.perl
The bag and mix get `.perl` in a form of `bag()`/`mix()`, but set gets dumped as either `().Set` or `set()` (kinda surprised `Set.new` and `set()` get dumped differently, given they compare `===` as True)

```
<Zoffix__> m: .perl.say for Set.new, Bag.new, Mix.new
<camelia> rakudo-moar e9351cbaa: OUTPUT: «().Set␤bag()␤mix()␤»
<Zoffix__> m: .perl.say for set(), bag(), mix()
<camelia> rakudo-moar e9351cbaa: OUTPUT: «set()␤bag()␤mix()␤»
<Zoffix__> m: dd set() === Set.new
<camelia> rakudo-moar e9351cbaa: OUTPUT: «Bool::True␤»
```

### PR DESCRIPTION
**Pull request by W4anD0eR96**
This will fix #1958

### CODE REVIEW

**Comment by lizmat** [comment]
FWIW, I seem to recall a reason to the inconsistency.  But don't have time to look at it in the next 48 hours.  Please refrain from merging until I've had time.

**Comment by zoffixznet** [comment]
> FWIW, I seem to recall a reason to the inconsistency. 

There's a related ticket that could use your input as well: https://github.com/rakudo/rakudo/issues/1959

**Comment by W4anD0eR96** [comment]
Let's say that `.gist` if for human readability, so consistency does no harm.

for `.perl`, `set()` is eqv to `().Set` and if it is not an empty set, nothing changed.

**Comment by zoffixznet** [comment]
> Let's say that .gist if for human readability, so consistency does no harm.

Comma-consistency looks to be all over the place:

```
$ perl6 -e '.say for <a b c>, [<a b c>], Blob.new(1, 2, 3), <a b b>.SetHash, <a b b>.BagHash, <a b b>.MixHash, set(<a b b>), bag(<a b b>), mix(<a b b>)'
(a b c)
[a b c]
Blob:0x<01 02 03>
SetHash(a b)
BagHash(a, b(2))
MixHash(a, b(2))
set(a b)
Bag(a, b(2))
Mix(a, b(2))
```

**Comment by W4anD0eR96** [comment]
@lizmat as a reminder.

**Comment by lizmat** [comment]
Not sure, but on 12 April I did this: c0212af9b91bd7f916c7e2  so I wonder what has changed now to make it inconsistent again?

**Comment by zoffixznet** [comment]
> so I wonder what has changed now to make it inconsistent again?

That commit doesn't affect the code path in the Issue.

Right now Set.perl checks `eqaddr` with `set()`, but Bag/Mix.perl doesn't do the same for `bag()`/`mix()`, which is where the inconsistency comes from.

However, that fact that `bag()`/`set()`/`mix()` always return the same object instead of creating a new one (which allows that `eqaddr` to work in the first place) IMO [is itself a bug](https://github.com/rakudo/rakudo/issues/1959).

So once [R#1959](https://github.com/rakudo/rakudo/issues/1959) is resolved, this inconsistency will also be resolved, and just the now-useless `.eqaddr` in `Set.perl` will need to be cleaned up.

**Comment by zoffixznet** [comment]
> There's a related ticket that could use your input as well: #1959

That's now resolved as not-a-bug, so it's fine for `set()`/`bag()`/`mix()` to be `.perl`'ed differently since in Rakudo we intern those.

The actual inconsistency now is that `Set.new` returns a separate object, but `Mix.new`/`Bag.new` return an interned copy. So we can "legally" make `Set.new` return an interned copy as well. I'll update the ticket with this info.

**Comment by lizmat** [comment]
AFAIK, Set.new / Bag.new / Mix.new return new instances.  Because this is what makes my %h is Set, my %h is Bag, my %h is Mix, work.

If we want go be a able to intern Set.new/Bag.new/Mix.new, we will need another way to fix my %h is … .

**Comment by W4anD0eR96** [comment]
> Set.new / Bag.new / Mix.new return new instances

FWIW, they all call `nqp::create(self)`

**Comment by lizmat** [comment]
Which is a new instance

**Comment by zoffixznet** [comment]
> but Mix.new/Bag.new return an interned copy

correction: they just `.perl` like `bag()`, but they return a new object.

```
m: say Bag.new.perl, Bag.new =:= bag()
rakudo-moar 587cd4f9e: OUTPUT: «bag()False␤»
```

**Comment by lizmat** [comment]
Ah that, will fix that.

**Comment by W4anD0eR96** [comment]
for 84f60adad10f04b3ffa4a5747af9820f8244c2a2

**Pull request closed without merging**
