### PR TITLE
Fix release pipeline to not delete the linux build

### PR DESCRIPTION
**Pull request by patrickbkr**

### CODE REVIEW

**Comment by Altai-man** [comment]
How can re re-run CI nicely?

**Comment by patrickbkr** [comment]
I just tried the suggestion of ugexe to create an empty commit to re-trigger the CI. It works, but the empty commit will stay around.

**Comment by JJ** [comment]
> I just tried the suggestion of ugexe to create an empty commit to re-trigger the CI. It works, but the empty commit will stay around.

Well, you can restart them in every one of the pages... Too much work, probably.

**Comment by Altai-man** [comment]
>I just tried the suggestion of ugexe to create an empty commit to re-trigger the CI. It works, but the empty commit will stay around

No, we can squash and merge, github even has UI for it. :) I'll do it once CI is green.

**Comment by patrickbkr** [comment]
@Altai-man I think the most obvious thing to do, when one wants to retrigger the CI because of new commits in master, is to just rebase and push. I just didn't think of that solution earlier. I'm pondering on these problems mostly because of [problem-solving#206](https://github.com/Raku/problem-solving/issues/206) at the moment.

**Comment by ugexe** [comment]
> I just tried the suggestion of ugexe to create an empty commit to re-trigger the CI. It works, but the empty commit will stay around

You avoid the empty commit with `--amend` if you are ok rewriting history (similarly to rebasing)

**Comment by patrickbkr** [comment]
> > I just tried the suggestion of ugexe to create an empty commit to re-trigger the CI. It works, but the empty commit will stay around
> 
> You can avoid the empty commit with `--amend` if you are ok rewriting history (similarly to rebasing)

Thanks for the hint!

**Pull request merged**
