### PR TITLE
Add tests for former REPL crashes

### PR DESCRIPTION
**Pull request by usev6**
We didn't have regression tests for evaluations that caused the REPL to crash badly.
The crashes are described in two bug reports from the old issue tracker:

* https://github.com/Raku/old-issue-tracker/issues/2917
* https://github.com/Raku/old-issue-tracker/issues/3254

See commits for some more details.

### CODE REVIEW

**Comment by vrurg** [comment]
May I ask you to have better description in the first comment and your commits in general? When PR is merged the comment is used as the default message for the merge commit. And overall, just referring to issues is not sufficient because the links may be gone with time (as it already happened with the old tracker). We even have a guide on writing good commit messages [here](https://github.com/rakudo/rakudo/blob/master/CONTRIBUTING.md#commit-messages)

**Review by vrurg — CHANGES_REQUESTED** [review]
Fix commit messages

**Comment by usev6** [comment]
I didn't realize that the first comment on a PR will be used as the default message for the merge commit. Thanks for pointing that out.

I kind of see your point, that the two commit messages are very terse (maybe overly terse). On the other hand the commits just added relatively simple tests that should be self-explaining. I was aware of our guide on writing good commit messages, but I didn't interpret it in a way, that the content of a referenced issue should be summed up in the commit message. Maybe the following part should be reworded to make that clearer:

> If you fixed a ticket, or the commit relates to a specific ticket, please mention the ticket in the title or the body as #12345 so that GitHub will automatically link to the corresponding issue. If there was an IRC conversation that can give some background or useful information, you can link to it by visiting the IRC logs and linking the link provided by the timestamps on the left side of the page.

I have to admit that your requests for ```better descriptions [...] in your commits in general``` hurts me a bit (the ```in general``` part). (At least usually) I try to write good commit messages -- but maybe I'm not able to meet the standards. I'll ponder on this a bit.
(Please note, that I'm fully aware that you -- or other reviewers -- have better things to do than trying to train people to write better commit messages. At my day job I'm the one who has to do that.)

**Comment by vrurg** [comment]
> I have to admit that your requests for `better descriptions [...] in your commits in general` hurts me a bit

Oops... I'm sorry as I didn't mean that! I only referred to the two commits of this PR because they're as terse the the PR comment. Not for a second I thought about any other ones than these two. I sincerely apologize for this! My certainly imperfect English plays some tricks with me sometimes too.

Also, there is no need to close this PR. The comment can be edited, the commits squashed, amended, and force-pushed back. That's what I'd do.

**Comment by usev6** [comment]
Thanks for clearing up the misunderstanding! So all is good :).
I'll rework the commits and this PR at a later time.

**Comment by usev6** [comment]
@vrurg I hope, I have addressed the points you raised and the current version is good to merge.

**Review by vrurg — APPROVED** [review]
Looks good. Thank you!

**Pull request merged**
