### PR TITLE
Use sh instead of bash

### PR DESCRIPTION
**Pull request by patzim**
Replaces all uses of bash with sh to be more portable. This relates to https://github.com/perl6/nqp/issues/528

### CODE REVIEW

**Comment by AlexDaniel** [comment]
```bash
target=$(command ls -l "$fname")
```
Even though ls itself is fragile, what about adding `--` before `"$fname"`?

**Comment by patzim** [comment]
@AlexDaniel What does '--' do with ls? It's not in the man page and seems to produce output identical to `ls -l` without the '--'.

**Comment by AlexDaniel** [comment]
@patzim same reason `--` is used everywhere else in the code. If your fname starts with `-`, then ls will do the wrong thing. Compare `ls -l -- -foo` and `ls -l -foo`.

I know that in general most kinda assume that filenames and paths are relatively sane, but the code here is consistently right with the use of quoting and `--` so that line looks kinda weird.

**Comment by AlexDaniel** [comment]
Ah, also here after `cd`
```
command cd "$(command dirname -- "$target")"
```

**Pull request merged**
