### PR TITLE
Fix/Implement RT #128097

### PR DESCRIPTION
**Pull request by MasterDuke17**

### CODE REVIEW

**Comment by labster** [comment]
`q/"$foo"/.IO.gist` will look a little funny, both before and after this PR, but I guess it is just `.gist`.

**Comment by lizmat** [comment]
Somehow, this got merged without github realizing it got merged

**Comment by MasterDuke17** [comment]
Not sure what you mean by merged without github realizing it? Nom currently has IO::Path.gist as:
```
multi method gist(IO::Path:D:) {
    qq|"$.abspath".IO|;
}
```
but the commit changes it to:
```
multi method gist(IO::Path:D:) {
    $!is-absolute
        ?? qq|"$.abspath".IO|
        !! qq|"$.path".IO|
}
```

**Comment by labster** [comment]
She meant that the issue didn't automagically close when the commit got merged.

**Comment by MasterDuke17** [comment]
Yeah, I'm just saying I don't see that the commit did get merged.

**Pull request closed without merging**
