### PR TITLE
Add method 'inode'

### PR DESCRIPTION
**Pull request by vrurg**
The syscall is already supported by nqp, no extra efforts needed.

### CODE REVIEW

**Review by lizmat — APPROVED** [review]

**Comment by jonathanstowe** [comment]
While you're in the mood, any chance of adding the `device` too (similarly already implemented in nqp,) I can rid my own implementations in `Linux::Fuser`  then :rofl:

**Comment by vrurg** [comment]
@jonathanstowe Not sure which one do you exactly mean, `st_dev` or `st_rdev`, so added both. :)

**Comment by jonathanstowe** [comment]
> which one do you exactly mean

`st_dev` - both `inode` and `st_dev` need to be compared to determined whether two "files" are actually the same thing.

Cheers!

**Comment by lizmat** [comment]
Hmmm... then maybe also throw in an `infix:<eqv>` candidate for `IO::Path` ?

**Comment by vrurg** [comment]
@lizmat one at a time. :) Though I'm not really sure about the semantics of `eqv`. It's somewhat fuzzy when it comes to options like symlinks, relative paths, etc. Apparently, inode and dev are the ultimate answer, but I'd rather consider options first.

**Comment by Xliff** [comment]
Any idea when these will be merged into master? I already have a use case. :)

**Comment by vrurg** [comment]
@Xliff I have certain doubts about the naming of `dev` method. Would like to give it another day to mull about, perhaps.

**Pull request merged**
