### PR TITLE
Test return constraints for role implementors

### PR DESCRIPTION
**Pull request by Altai-man**
Closes https://github.com/rakudo/rakudo/issues/2385

The failed tests are all different and appear to be flappers to me...

### CODE REVIEW

**Comment by AlexDaniel** [comment]
After a discussion on IRC, I think testing the error message is fine in rakudo tests but we also need a roast test too, somewhere around here: https://github.com/perl6/roast/blob/93cc2e4274df21e9bb7ff485acfc5279305ba87c/S14-roles/composition.t#L179 (we already have similar tests that don't consider return types, and that should be fixed).

**Comment by Altai-man** [comment]
Was writing a test and now I am confused:
```
> role R5 { method m-ret(--> Int) { ... } }
(R5)
> class C11 does R5 { method m-ret() { 99 } }
(C11)
> C11.m-ret;
99
> 
```
should not we throw an error here?

**Comment by FCO** [comment]
We should throw an error if 2 roles implement the same method, but the way to fix it is to write it on the class if I remember it well

**Comment by JJ** [comment]
> Was writing a test and now I am confused:
> 
> ```
> > role R5 { method m-ret(--> Int) { ... } }
> (R5)
> > class C11 does R5 { method m-ret() { 99 } }
> (C11)
> > C11.m-ret;
> 99
> > 
> ```
> 
> should not we throw an error here?

But this is a different issue, right?

Also, can you check the CI errors?

**Comment by lizmat** [comment]
Awaiting CI results now

**Pull request merged**
