### PR TITLE
IO::Socket::INET Bug fixes. 

### PR DESCRIPTION
**Pull request by dugword**
* Fixed bug where IPv6 URIs were not parsed correctly when passed as host:port (E.g. "[::1]:3000").
* Split new method into a multi method with type constraints.
* Now fails when invalid family or port values are passed.
* Added constants for MIN and MAX port values

RT
   [perl #130473]
   [perl #130474]
   [perl #130475]

### CODE REVIEW

**Comment by dugword** [comment]
$ make t/spec/S32-io/IO-Socket-INET.t

All tests successful.
Files=1, Tests=50, 16 wallclock secs ( 0.02 usr  0.00 sys + 10.37 cusr  0.92 csys = 11.31 CPU)
Result: PASS
Success!

**Comment by dugword** [comment]
Needs additional changes

**Comment by dugword** [comment]
Identified bugs fixed/

**Comment by dugword** [comment]
Additional issues identified

notviki
dugword: so one issue is Str:D :$localhost! needs to be Str :$localhost
notviki
dugword: and the other issue is then you pass undefined args to split-host-port/v4-split and it throws

**Comment by ugexe** [comment]
I don't think you can remove port 80 as a default without breaking multiple modules in the ecosystem

**Comment by zoffixznet** [comment]
Which modules are these?

The 80 default worked only via new, not via connect.

**Comment by ugexe** [comment]
Dunno, hence the 'think', but changing an interface's behavior where its common to follow a pattern such as `My::IO::Wrapper.new( socket => IO::Socket::INET.new(...) )` seems like a bad idea. I can say I have "darkpan" code that does this, and both OpenSSL/IO::Socket::SSL and Net::HTTP follow that pattern (although these do initialize the port).

**Comment by zoffixznet** [comment]
From user's perspective we're not changing anything.

**Comment by dugword** [comment]
$ make t/spec/S32-io/socket-accept-and-working-threads.t
```
rm -f -- perl6
cp -- perl6-m perl6
chmod -- 755 perl6
/usr/local/Cellar/perl/5.24.0_1/bin/perl t/harness5 --fudge --moar --keep-exit-code --verbosity=1 t/spec/S32-io/socket-accept-and-working-threads.t
t/spec/S32-io/socket-accept-and-working-threads.t ..
1..10
ok 1 - Server responded (0)
ok 2 - Server responded (1)
ok 3 - Server responded (2)
ok 4 - Server responded (3)
ok 5 - Server responded (4)
ok 6 - Started work was completed (0)
ok 7 - Started work was completed (1)
ok 8 - Started work was completed (2)
ok 9 - Started work was completed (3)
ok 10 - Started work was completed (4)
ok
All tests successful.
Files=1, Tests=10,  4 wallclock secs ( 0.03 usr  0.01 sys +  4.98 cusr  1.14 csys =  6.16 CPU)
Result: PASS
```

Previously failing tests now pass

**Pull request merged**
