### PR TITLE
Make short-id2class accessible

### PR DESCRIPTION
**Pull request by MadcapJake**
Previously it was impossible to add a custom CUR but with this change, you can add your CUR to the registry of short-ids.

I know that the plan is to change how CURs are loaded so this is a stopgap until that implementation.

### CODE REVIEW

**Comment by niner** [comment]
This makes short-id2class a public interface that we will have to support. I'd much rather see work towards a real designed solution.

**Comment by MadcapJake** [comment]
We could mark it as deprecated. I think there needs to at least be a solution until the real one is made available. Right now it just doesn't work without this.

**Comment by MadcapJake** [comment]
Perhaps if it was moved it to an experimental package we could merge this.  @niner, would that be acceptable? This way it would imply that the feature should not be depended on because it will be changing.
```perl6
use experimental :cur;
use CompUnit::Repository::GX;
use Foo::Bar;
```

**Comment by JJ** [comment]
Closed after opening Raku/problem-solving#189

**Pull request closed without merging**
