### PR TITLE
Fix table caption RT #126740

### PR DESCRIPTION
**Pull request by tbrowder**
appropriate tests are in a roast PR

### CODE REVIEW

**Comment by tbrowder** [comment]
The changes to Actions.nqp were required to get rid of a conflict—they have no part in my PR.

**Comment by tbrowder** [comment]
Note the caption quote issue is another bug: RT #126742.

**Comment by AlexDaniel** [comment]
What'd be the output of ``:bar<"meow">``?

**Comment by tbrowder** [comment]
output of bar<“meow”>?

good question—I’ll add to tests and see...

**Comment by tbrowder** [comment]
I don’t know. As Zoffix pointed out the scary TODO comments indicate some fragile handling—and I don’t yet understand how the value is actually extracted.  I will play around with other nqp code to see how various things work.

**Comment by tbrowder** [comment]
TODO Update affected tickets to show incompleteness of fixes.

**Comment by AlexDaniel** [comment]
**⚠⚠⚠** Rerevert https://github.com/perl6/roast/pull/363 once this PR is merged (it was merged a bit too early by mistake, then reverted)

**Comment by tbrowder** [comment]
I’m closing this PR for now and will resubmit later in improved form.

**Pull request closed without merging**
