### PR TITLE
Fix RT#127958 on moarvm... :D smiley containers assigned from Nil

### PR DESCRIPTION
**Pull request by skids**
There is no sensible default default for :D types, blame Kurt Gödel.
  This breaks the assumption that a type's default is a legal value.
  So, check the assigned type even when assigning from the_default.

### CODE REVIEW

**Comment by skids** [comment]
Passed roast master and 6.c-errata.
JVM/JS fixes may also be needed.

**Comment by gfldex** [comment]
judgment was spoken see: https://rt.perl.org/Public/Bug/Display.html?id=127958

**Comment by lizmat** [comment]
No todoed tests passed  :-(

**Comment by LLFourn** [comment]
Tests: https://github.com/perl6/roast/commit/fa9a6b05f665bef3b5b45cb35d4018b2a8368c31

**Pull request merged**
