### PR TITLE
Use new stat syscalls

### PR DESCRIPTION
**Pull request by MasterDuke17**
A second version of https://github.com/rakudo/rakudo/pull/5316 (performance is the same) that requires https://github.com/MoarVM/MoarVM/pull/1766 for the MoarVM implementations of the syscalls.

### CODE REVIEW

**Review by ugexe — APPROVED** [review]
Nice!

**Comment by vrurg** [comment]
What about JVM backend?

**Comment by Leont** [comment]
I've been wanting this for `Path::Finder` for years, good work

**Comment by MasterDuke17** [comment]
Arg! Guess I’ll have to wrap the changes in ‘#if moar’.

**Pull request merged**
