### PR TITLE
RT#126785: ensure make *test uses -Ilib rather than preinstalled libs

### PR DESCRIPTION
**Pull request by ungrim97**

### CODE REVIEW

**Comment by niner** [comment]
This can't be right. $(PERL) is the perl 5 executable while lib contains Perl 6 libs. perl -Ilib -e 'use Test;' fails accordingly.

**Comment by ungrim97** [comment]
This ensures that the right libs are passed to tap harness which seems happy to pass them on when it runs:

/home/mfrancis/dotfiles/anyenv/envs/plenv/versions/5.22.0/bin/perl5.22.0 -Ilib t/harness --moar t/01-sanity t/04-nativec
all

**Comment by ungrim97** [comment]
Hmm looking at t/harness however it would seem that this is already being done by PERL6LIB on line 44?

**Comment by jnthn** [comment]
Wouldn't this require you to have to "make install" before you can "make
test"?

**Pull request closed without merging**
