### PR TITLE
Allow negative Unix (POSIX) values for DateTime instantiation

### PR DESCRIPTION
**Pull request by tbrowder**
The purpose of this PR is to allow negative Unix epoch values to be used so dates earlier than the Unix epoch can be instantiated with instants from older epochs, particulary the Julian date epoch.

### CODE REVIEW

**Comment by lizmat** [comment]
I would put the code handling `epoch < 0` into a separate private method (e.g. `!bc`, and then do something like:

    return self!bc($epoch) if $epoch < 0;

**Comment by tbrowder** [comment]
> I would put the code handling `epoch < 0` into a separate private method (e.g. `!bc`, and then do something like:
> 
> ```
> return self!bc($epoch) if $epoch < 0;
> ```

Good idea, WILCO!

**Comment by tbrowder** [comment]
I lied on #raku-dev. I had not installed my change before testing. Fundamentally the problem is DateTime's handling of negative dates is the break point, not negative epochs. I made another epoch defined at 0001-01-01T00:00:00Z and compare unix epochs against it. All epochs >= to it are handled as usual, but epochs less than that get the special handling.

Given that change, all current spectests pass, as well as the few tests I have created but not added to roast yet.

Now I will work on adding tests across the new domain of, say, years -4000 to +4000.

**Comment by tbrowder** [comment]
I'm discovering more nuances in the current code that interfere with my approach. For one thing, my experiments show that the Claus Tondering algorithm implementation is wrong. I believe the algorithms by Meeus (as used in Perl's Astro::Montenbruck by Sergey Krushinsky) are the ones to be used. 

I am closing this PR to work on another attempt after @MasterDuke17's PRs are merged.

**Pull request closed without merging**
