### PR TITLE
Fix windows process quoting bug (#3761)

### LINKED ISSUE #3761: rakudo/repl.t fails consistently on Windows
See [log](https://dev.azure.com/Rakudo/rakudo/_build/results?buildId=170&view=logs&j=70f6b8a1-f3cf-5727-bd79-d08ddb1caf67&t=f59a17df-92a9-5d7f-18bb-7f81f1c720a8) on Azure for details.

[Here](https://dev.azure.com/Rakudo/rakudo/_build/results?buildId=127&view=results) (commit https://github.com/rakudo/rakudo/commit/cde948aee058ecddf7cbfe69f38754cab19ab642) it still worked, but starting from https://github.com/rakudo/rakudo/pull/3576 the test starts to fail.

Ping @patrickbkr.

### PR DESCRIPTION
**Pull request by ugexe**
Resolves #3761

### CODE REVIEW

**Comment by ugexe** [comment]
untested

**Comment by Altai-man** [comment]
This indeed fixes tests on Windows. JVM builds are long, but let's wait for them before merging.

**Comment by Altai-man** [comment]
Thank you!

**Comment by patrickbkr** [comment]
@ugexe Thanks for fixing my stuff!

**Pull request merged**
