### PR TITLE
REPL: exit by pressing ^D twice, not once

### PR DESCRIPTION
**Pull request by Kaiepi**
This allows clearing the current line without exiting and prevents typos
from forcing it to exit.

### CODE REVIEW

**Comment by Kaiepi** [comment]
Do not merge this. This has only been tested with Linenoise, and I know it's possible to do with Readline, but isn't as it stands.

**Comment by Kaiepi** [comment]
Closing this since it doesn't work with the default line editor, and can't test Readline since it doesn't get used even when I force it to with env flags.

**Comment by Kaiepi** [comment]
Tested Readline. Using ^D like this works

**Comment by Kaiepi** [comment]
Updated with checks for ^D/^Z depending on OS

**Comment by JJ** [comment]
Sorry, seems to have conflicts. Can you please check and fix them?

**Comment by vrurg** [comment]
Considering that `^Z` support for Windows is already implemented, we probably only need lines 317-332 of the patch.

**Comment by lizmat** [comment]
Is this PR salvageable?

**Pull request closed without merging**
