### PR TITLE
Convert more BOOTSTRAPATTRs to Attributes

### PR DESCRIPTION
**Pull request by MasterDuke17**
This is a second pass, changing individual instances of BOOTSTRAPATTR to
Attributes even if not all for a class could be converted. Additionally,
this includes a change to scalar_attr() to permit creating Attributes
without setting :auto_viv_container.

The change to Code's $!compstuff allows the JVM build to compile;
however, the install still fails with 'Flattening named argument must
have VMHash REPR'.

Passes `make spectest` on Moar.

### CODE REVIEW

**Comment by MasterDuke17** [comment]
Not sure about the AppVeyor builds, it passes `make coretest` on Moar for me.

**Comment by MasterDuke17** [comment]
Ugh, this is what I get for trying to sync Moar and JVM development and testing late at night. If you just apply the Code.HOW change, you get the JVM behavior like I described. However, the complete PR now gives:

/home/dan/Source/perl6/rakudo-j/install/bin/nqp-j --target=jar --output=blib/Perl6/Compiler.jar --encoding=utf8 \
    src/Perl6/Compiler.nqp
java.lang.NullPointerException
  in  (gen/jvm/Perl6-Optimizer.nqp)
  in  (gen/jvm/Perl6-Optimizer.nqp)
  in  (gen/jvm/Perl6-Optimizer.nqp)
  in  (src/vm/jvm/ModuleLoader.nqp:78)
  in load_module (src/vm/jvm/ModuleLoader.nqp:60)
  in load_module (gen/jvm/stage2/NQP.nqp:287)
  in statement_control:sym<use> (gen/jvm/stage2/NQP.nqp:2378)
  in !reduce (gen/jvm/stage2/QRegex.nqp:1340)
  in !cursor_pass (gen/jvm/stage2/QRegex.nqp:1301)
  in statement_control:sym<use> (gen/jvm/stage2/NQP.nqp)
  in !protoregex (gen/jvm/stage2/QRegex.nqp:1377)
  in statement_control (gen/jvm/stage2/NQP.nqp)
  in statement (gen/jvm/stage2/NQP.nqp:946)
  in statementlist (gen/jvm/stage2/NQP.nqp)
  in comp_unit (gen/jvm/stage2/NQP.nqp:916)
  in TOP (gen/jvm/stage2/NQP.nqp:814)
  in parse (gen/jvm/stage2/QRegex.nqp:2093)
  in parse (gen/jvm/stage2/NQPHLL.nqp:1400)
  in compile (gen/jvm/stage2/NQPHLL.nqp:1356)
  in eval (gen/jvm/stage2/NQPHLL.nqp:1092)
  in evalfiles (gen/jvm/stage2/NQPHLL.nqp:1313)
  in command_eval (gen/jvm/stage2/NQPHLL.nqp:1207)
  in command_line (gen/jvm/stage2/NQPHLL.nqp:1181)
  in MAIN (gen/jvm/stage2/NQP.nqp:4058)
  in <mainline> (gen/jvm/stage2/NQP.nqp:4054)
  in  (gen/jvm/stage2/NQP.nqp)

**Comment by lizmat** [comment]
So, what is the state of this PR ??

If I revert e8c8af60c40bbbee2c9dd8d63bb9fb75fe065e30 , the JVM builds fine again.  Which we would need for a release.

**Comment by MasterDuke17** [comment]
I'm continuing to try and find a solution that isn't just copying back in the old code and having an `#?if moar ... #?endif ... #?if jvm ... #?endif`. However, I haven't had much success so far, so it's probably best to revert e8c8af6 before the release and hopefully I'll just resubmit has a comprehensive change.

**Comment by zoffixznet** [comment]
Reverted in https://github.com/rakudo/rakudo/commit/2d5a2c9d16

**Pull request closed without merging**
