### PR TITLE
Fix RT#126669

### PR DESCRIPTION
**Pull request by titsuki**
Hi,

I fixed RT#126669: https://rt.perl.org/Public/Bug/Display.html?id=126669

The changes are:
+ Add error messages for Perl5-style pragma (e.g., "use 6.0", "need 6.0") [2dc93ac]
+ Add tests for X::Undeclared::Symbols exception for when Perl5-style pragma is used [4ec5936]

### CODE REVIEW

**Comment by lizmat** [comment]
Thanks!

**Comment by titsuki** [comment]
Thanks for merging!

**Comment by zoffixznet** [comment]
FWIW, `need` does not load the language and just silently ignores the version:

```
<Zoffix_> m: need v6.z
<camelia> rakudo-moar 1e8c9762e: ( no output )
<Zoffix_> m: use v6.z
<camelia> rakudo-moar 1e8c9762e: OUTPUT: «===SORRY!=== Error while compiling <tmp>␤No compiler available for Perl v6.z␤at <tmp>:1␤------> use v6.z⏏<EOL>␤»
```

There's [a ticket proposing removal of `<version>` token from its parse](https://rt.perl.org/Ticket/Display.html?id=132214#ticket-history)

**Comment by titsuki** [comment]
@zoffixznet 
Thanks! 
I'll send a PR for RT132214.

**Pull request merged**
