### PR TITLE
Add NFC/NFD/NFKC/NFKD as subs

### PR DESCRIPTION
**Pull request by lizmat**
These functions were only available as Cool.methods.  This makes them
also available as subs for consistency.

Also contains changes to tests for the now globally visible subs.

### CODE REVIEW

**Comment by jnthn** [comment]
Should they not just work "naturally" (and with identical syntax) as type coercions?

**Comment by lizmat** [comment]
You mean something like `my NFC() @a = "foobar";`  ??

**Comment by jonathanstowe** [comment]
It already works as a coercion:

```
raku -e 'say NFC("foobars")'
NFC:0x<0066 006f 006f 0062 0061 0072 0073>
```

**Comment by lizmat** [comment]
Well, yes, but I guess we need the sub versions for introspection?

**Comment by jnthn** [comment]
> Well, yes, but I guess we need the sub versions for introspection?

The types in scope are just as introspectable, I think?

**Comment by lizmat** [comment]
I guess  :-)

**Pull request closed without merging**
