### PR TITLE
Update to Unicode 15.0

### PR DESCRIPTION
**Pull request by thundergnat**
Basically just adding Unicode 15.0 database and updating test data pointer.

MoarVM pull request https://github.com/MoarVM/MoarVM/pull/1737 will need to be applied before this will pass testing.

### CODE REVIEW

**Comment by MasterDuke17** [comment]
There has been idle speculation about adding some sort of `use Unicode v<n>` capability to Rakudo. If that's ever implemented, would it be easy to backfill in Unicode 14 if we skip straight from 13 to 15? Or should we update to 14 and then immediately to 15?

**Comment by thundergnat** [comment]
There is no infrastructure in place to do that right now. If we do go that route, it will be simple to just download the relevant
data from the Unicode consortium site. There is already a property available through .uniprop() that tells you when (in which revision) a particular codepoint was added. That won't help much with changing composition and grapheme break rules though.

**Comment by thundergnat** [comment]
Something I think would be quite useful, and should be fairly straightforward to add would be a $*UNIVER ($*UNICODE-VERSION ?) variable that you could query to see what version of Unicode we are presently using.

**Comment by lizmat** [comment]
If there's some nqp::code to obtain the unicode version, we could expose that as `$?UNICODE-VERSION`.  It would be a compile time variable, as we cannot switch unicode versions at runtime, can we?

**Comment by thundergnat** [comment]
> It would be a compile time variable, as we cannot switch unicode versions at runtime, can we?

Correct. It would need to be compile time (for the near future at least.) Probably as simple as setting up a dynamic variable, and manually updating it whenever we switch versions.

**Comment by lizmat** [comment]
@thundergnat but how to get at that version number?  Check all the codepoints for that unicode version property and pick the highest?  That feels...  hackish   :-)

**Comment by lizmat** [comment]
See also #5153

**Review by lizmat — APPROVED** [review]

**Comment by lizmat** [comment]
Manually committed this in https://github.com/rakudo/rakudo/commit/37826798b4 as this PR was based on the now obsolete master branch

**Pull request closed without merging**
