### PR TITLE
Raku to rakudo executable

### PR DESCRIPTION
**Pull request by sumanstats**
As discussed here in https://github.com/rakudo/rakudo/pull/3642
and mentioned in https://github.com/Raku/problem-solving/blob/master/solutions/language/Path-to-Raku.md#executables
rakudo is executable and raku is symlink.

Reflect that change with this pull request.

### CODE REVIEW

**Comment by AlexDaniel** [comment]
> Note that different backends implement slightly different sets of
features. For a high-level overview of implemented and missing features,
please visit [the features page on raku.org](https://perl6.org/compilers/features).

This link is down and I'm pretty sure even when it was up it was quite outdated. Let's remove this paragraph perhaps?

**Comment by AlexDaniel** [comment]
> To receive important notifications from the core developer team, please
subscribe to [the p6lert service](https://alerts.perl6.org) using the RSS feed,
twitter, or [the p6lert commandline script](https://github.com/raku-community-modules/perl6-p6lert).

This was an interesting project and I wish it was still up, but it currently isn't. Maybe remove the mention of it for now?

**Comment by AlexDaniel** [comment]
> By supplying combinations of backends to the `--backends` flag, you
can get two or three backends built in the same prefix. The first
backend you supply in the list is the one that gets the `perl6` name
as a symlink, and all backends are installed separately as
`perl6-m` or `perl6-j` for Rakudo on
MoarVM, or JVM respectively.

Are these `rakudo-m`, `rakudo-j`, etc.? Or do we still generate `perl6-j` files?

**Comment by sumanstats** [comment]
> > Note that different backends implement slightly different sets of
> > features. For a high-level overview of implemented and missing features,
> > please visit [the features page on raku.org](https://perl6.org/compilers/features).
> 
> This link is down and I'm pretty sure even when it was up it was quite outdated. Let's remove this paragraph perhaps?

Can we keep this historical list of compilers https://www.raku.org/compilers/ or not mention it altogether.

**Comment by sumanstats** [comment]
> > By supplying combinations of backends to the `--backends` flag, you
> > can get two or three backends built in the same prefix. The first
> > backend you supply in the list is the one that gets the `perl6` name
> > as a symlink, and all backends are installed separately as
> > `perl6-m` or `perl6-j` for Rakudo on
> > MoarVM, or JVM respectively.
> 
> Are these `rakudo-m`, `rakudo-j`, etc.? Or do we still generate `perl6-j` files?

Running `perl Configure.pl --backends=moar,jvm` throws this error,

```
root@a767109bd8e9:/rakudo# perl Configure.pl --backends=moar,jvm
===ATTENTION===
  No --prefix supplied, building and installing to /rakudo/install
No pre-existing installed file found at /rakudo/install/bin/nqp-m
No pre-existing installed file found at /rakudo/install/bin/nqp-j
No pre-existing installed file found at /rakudo/install/bin/nqp-m
No pre-existing installed file found at /rakudo/install/bin/nqp-j
Use of uninitialized value $str in substitution (s///) at /rakudo/3rdparty/nqp-configure/lib/NQP/Config.pm line 1420.
Use of uninitialized value $str in substitution (s///) at /rakudo/3rdparty/nqp-configure/lib/NQP/Config.pm line 1421.
Use of uninitialized value in concatenation (.) or string at /rakudo/tools/lib/NQP/Config/Rakudo.pm line 361.
Use of uninitialized value in quotemeta at /rakudo/tools/lib/NQP/Config/Rakudo.pm line 371.
Use of uninitialized value in substitution (s///) at /rakudo/tools/lib/NQP/Config/Rakudo.pm line 371.
Use of uninitialized value in substitution (s///) at /rakudo/tools/lib/NQP/Config/Rakudo.pm line 371.
Use of uninitialized value in quotemeta at /rakudo/tools/lib/NQP/Config/Rakudo.pm line 373.
Use of uninitialized value in concatenation (.) or string at /rakudo/tools/lib/NQP/Config/Rakudo.pm line 379.
Use of uninitialized value in sprintf at /rakudo/tools/lib/NQP/Config/Rakudo.pm line 414.
Redundant argument in sprintf at /rakudo/tools/lib/NQP/Config/Rakudo.pm line 414.
Use of uninitialized value in concatenation (.) or string at /rakudo/tools/lib/NQP/Config/Rakudo.pm line 423.
Use of uninitialized value in concatenation (.) or string at /rakudo/tools/lib/NQP/Config/Rakudo.pm line 423.
Using /rakudo/install/bin/nqp-m (version  / MoarVM ).
Use of uninitialized value in sprintf at /rakudo/tools/lib/NQP/Config/Rakudo.pm line 428.
Redundant argument in sprintf at /rakudo/tools/lib/NQP/Config/Rakudo.pm line 428.
===SORRY!===
  jvm::runtime.jars value not available from /rakudo/install/bin/nqp-j --show-config.
  
  To automatically clone (git) and build a copy of NQP 2020.02.1-154-ga7b0b7be2,
  try re-running Configure.pl with the '--gen-moar' option.
  Or, use '--prefix=' to explicitly specify the path where the NQP and MoarVM
  executables can be found that are use to build Rakudo. at /rakudo/3rdparty/nqp-configure/lib/NQP/Config.pm line 192.
 at /rakudo/3rdparty/nqp-configure/lib/NQP/Config.pm line 34.
        NQP::Config::__ANON__("===SORRY!===\x{a}  jvm::runtime.jars value not available from /ra"...) called at /rakudo/3rdparty/nqp-configure/lib/NQP/Config.pm line 192
        NQP::Config::sorry(NQP::Config::Rakudo=HASH(0x55abeb7b7258), "jvm::runtime.jars value not available from /rakudo/install/bi"..., "\x{a}To automatically clone (git) and build a copy of NQP 2020.02"..., "try re-running Configure.pl with the '--gen-moar' option.", "Or, use '--prefix=' to explicitly specify the path where the "..., "executables can be found that are use to build Rakudo.") called at /rakudo/tools/lib/NQP/Config/Rakudo.pm line 576
        NQP::Config::Rakudo::post_active_backends(NQP::Config::Rakudo=HASH(0x55abeb7b7258)) called at /rakudo/3rdparty/nqp-configure/lib/NQP/Config.pm line 660
        NQP::Config::configure_active_backends(NQP::Config::Rakudo=HASH(0x55abeb7b7258)) called at /rakudo/tools/lib/NQP/Config/Rakudo.pm line 473
        NQP::Config::Rakudo::configure_active_backends(NQP::Config::Rakudo=HASH(0x55abeb7b7258)) called at Configure.pl line 102
```

I think its better to remove this para 
> Multiple backends at the same time
> By supplying combinations of backends to the --backends flag, you can get two or three backends built in the same prefix. The first backend you supply in the list is the one that gets the perl6 name as a symlink, and all backends are installed separately as perl6-m or perl6-j for Rakudo on MoarVM, or JVM respectively.

What is your thought ?

**Comment by sumanstats** [comment]
I have made a number of changes in README.md and Contributing.md. For multiple backends please see here https://stackoverflow.com/questions/61430360/building-multiple-backends-for-raku-fails/

In multiple backends, rakudo-m, rakudo-j are generated, that I have added in README.md.

**Comment by AlexDaniel** [comment]
There were some conflicts, but all is fixed now and the changes were merged. Thanks!

**Pull request closed without merging**
