### PR TITLE
Add IO::Path.user/group methods

### PR DESCRIPTION
**Pull request by lizmat**
- .user returns the uid of the path, or a failure if it doesn't exist
- .group returns the gid of the path, or a failure if it doesn't exist

This basically exposes the nqp::const::STAT_UID and nqp::const::STAT_GID
slots of nqp::stat.

I did consider making these allomorphs with the user / group name in string
format as well, but that turned out to be pretty difficult to do without
NativeCall or calling some external program to get the group name.

I also have no idea what these nqp::stat slots mean on Windows.

Lack of this functionality mentioned in some private email conversations
with a sysadmin wanting to use Raku more.

### CODE REVIEW

**Review by vrurg — APPROVED** [review]

**Comment by vrurg** [comment]
I guess, `nqp::stat` will work for Win* and other non-unix OSes, won't it?

**Comment by lizmat** [comment]
I would hope so, but am not in a position to test.

**Comment by vrurg** [comment]
I have checked it with MoarVM, the op falls back to libuv. So, once again we're in position of supporting OSes supported by the lib. Fair enough.

**Comment by Leont** [comment]
Yes, I have needed this (and resorted to using nqp to get around it). This is a welcome change :-)

**Pull request merged**
