### PR TITLE
Try fixing closed handle operations error

### PR DESCRIPTION
**Pull request by voldenet**
This tries solving the problem described in bug #3073.

It has not been thoroughly tested, there are a few problems with this:
- new method naming
- race condition when closing/destroying handle: `$!decoder` is `Encoding::Decoder`, `$!PIO` is not null
- wrong exception because of race condition: `$!decoder` is not null (set by seek), `$!PIO` is null
- missing "closed handle" errors for a few methods

### CODE REVIEW

**Comment by voldenet** [comment]
There were changes in error message, I've changed relevant test for now, but in this case similar languages do this:
- python/ruby - high level object is closed: `I/O operation on closed file`, `'read': closed stream (IOError)`
- nodejs/perl/golang/C - low level object is invalid: `EBADF`, `Bad file descriptor`

**Comment by voldenet** [comment]
As written before, there are still some lingering errors, but solving them would introduce additional overhead into basic IO methods, impacting overall performance. It might be better to turn that message into EBADF inside MoarVM.

- `encoding` should fail when there are bytes available in the decoder, because `nqp::seekfh` would be used
- seek: `seek requires an object with REPR MVMOSHandle (got VMNull with REPR Null)`
- tell: `tell requires an object with REPR MVMOSHandle (got VMNull with REPR Null)`
- slurp: `read bytes requires an object with REPR MVMOSHandle (got VMNull with REPR Null)`
- WRITE: `write bytes requires an object with REPR MVMOSHandle (got VMNull with REPR Null)`
- READ: `read bytes requires an object with REPR MVMOSHandle (got VMNull with REPR Null)`
- lock: `get native descriptor requires an object with REPR MVMOSHandle (got VMNull with REPR Null)`
- unlock: `get native descriptor requires an object with REPR MVMOSHandle (got VMNull with REPR Null)`

**Comment by JJ** [comment]
Can you please try and fix the conflicts?

**Comment by voldenet** [comment]
I've fixed the conflicts

**Comment by lizmat** [comment]
Looks like this was effectively implemented with 3865f1caee so closing this now

**Pull request closed without merging**
