### PR TITLE
Make (Set|Bag|Mix)(Hash)? stringification the same

### PR DESCRIPTION
**Pull request by MasterDuke17**
perlawhirl++ for the find.

Rakudo build ok and passes `make m-test m-spectest`.

### CODE REVIEW

**Comment by 0racle** [comment]
irclog link for context

https://irclog.perlgeek.de/perl6/2018-04-10#i_16027887

**Comment by lizmat** [comment]
No, this is intentional, because the semantics of `Bag()` and `bag()` are different.

`bag(<a b c>)` takes *all* values at face value and puts it in the bag.

`Bag( <a b c> )` looks at the values and tries to interpret them as `Pair`s if possible.

Note the difference in behaviour:

    $ 6 'dd bag((a => 42, a=> 42))'
    (:a(42)=>2).Bag

    $ 6 'dd Bag((a => 42, a=> 42))'
    ("a"=>84).Bag

**Comment by AlexDaniel** [comment]
By the way, we also have this ticket: [RT #132281](https://rt.perl.org/Ticket/Display.html?id=132281). Please do something with it also when there's a final decision on this PR.

**Comment by lizmat** [comment]
I'm going to close this PR on the following grounds:

- .perl bag/mix *must* be lowercase because of their semantics
- .perl on set *could* be uppercase, but seems more consistent to also keep that lowercase
- adding a comma in .gist on set seems to me a loss of real-estate.  As discussed in other places, .gist is for human consumption.  Separating on space seems logical to me.  But on that last point I could be persuaded by others to add the comma.

**Pull request closed without merging**
