### PR TITLE
Remove say/note (\x) multi candidate too

### PR DESCRIPTION
**Pull request by zhuomingliang**

### CODE REVIEW

**Comment by FROGGS** [comment]
What is the motivation to remove them?

**Comment by jnthn** [comment]
They are there for performance reasons; I'd prefer they stay.

**Comment by zhuomingliang** [comment]
@jnthn how about https://github.com/rakudo/rakudo/commit/5c0c7bcfe0670ad51d6ee029cbb29ca2711efd89 ?

**Comment by moritz** [comment]
I removed the `print` candidate, because with it, `my @array = <a b>; print @array` produces a space between `a` and `b`, which seems wrong. Having the slurpy handle the array case fixes it.

**Comment by jnthn** [comment]
Makes sense for print, but isn't changing it for say/note not just foolish
consistency (e.g. silly)?

**Pull request closed without merging**
