### PR TITLE
Issue 1238: Fix Hash clone not retaining all attributes

### PR DESCRIPTION
**Pull request by jstuder-gh**
Addresses [Issue 1238](https://github.com/rakudo/rakudo/issues/1238).

This issue was occurring due to the an operation that takes place in the
Hash 'but' method. A cloning of the Hash obj occurs but not all the
attributes are being replicated in the clone.

Mirroring (almost) the logic of the Mu clone method so that all
attributes are replicated on the new clone obj, not just $!storage.
However, unlike in Mu, not cloning the $!storage Scalar container (the
.VAR on the attribute) to avoid causing a regression for the issue fixed
in commit 6b2b34a79150f6e9a275fd39eb5dd96519d6179f.

### CODE REVIEW

**Comment by jstuder-gh** [comment]
Requires tests be added to the roast, if accepted.

**Comment by lizmat** [comment]
Thanks for looking into this!

`clone` is supposed a fast, low level way of cloning an object.  By copying the logic from `Mu`, you're essentially ignoring all of the knowledge we have of the `Hash` object, namely that it also has a `$!descriptor`.  And performance wise, there is now no difference between having this method, and not having this method (aka, removing `Hash.clone` altogether).

I think it should be sufficient to make sure the same `$!descriptor` is used in the cloned `Hash` object.  Please adjust your pull request accordingly, and I'll make sure it will get merged.

**Comment by jstuder-gh** [comment]
I tried just binding the `$!storage` and `$!descriptor` attributes only, but unfortunately the result when calling the `.a` accessor was still `(Any)`, (given the example included in the issue).

I suppose we could query the roles that are mixed into the object and bind the non-standard attributes to the new object. That would make it so that we don't have to bind all the attributes.

Ignore the high-level Perl 6, I'm just thinking in terms of the end result. I'd ultimately implement in a lower-level nqp style, of course.

```
nqp::bindattr($cloned, Map,  '$!storage',    nqp::clone( nqp::getattr(self, Map, '$!storage')) );
nqp::bindattr($cloned, Hash, '$!descriptor', nqp::clone( nqp::getattr(self, Hash, '$!descriptor')) );

my @attrs = self.^roles.grep( * ~~ none Associative, Iterable )
                .map( *.^attributes.unique.Slip );

for @attrs -> $attr {
    unless nqp::objprimspec($attr.type) {
        my $name     := $attr.name;
        my $package  := $attr.package;
        if nqp::attrinited(self, $package, $name) {
            my $attr_val := nqp::getattr($cloned, $package, $name);
            nqp::bindattr($cloned, $package, $name, nqp::clone($attr_val));
        }
    }
}
```

Although, I suspect that after iterating through the roles then through the attributes, it wouldn't really be any faster than iterating through the attributes on the initial object and binding them on the new (as in the Mu implementation).

What do you think?

**Comment by jstuder-gh** [comment]
I realize now that I was coming at this from the wrong angle before.

I had also committed it on top of the master branch. I had forgotten this fact so when I force pushed the real master to my fork it wiped the ref to the of the old commit on Github, so why keep this open.

I might return to this issue again at some point in the future, and at that time I will open another PR.

**Pull request closed without merging**
