### PR TITLE
Revert "Add new routine 'frac'"

### PR DESCRIPTION
**Pull request by tbrowder**
Reverts rakudo/rakudo#4244

Too much discovered too late, and I acted too hastily. The issue needs more discussion. See references with issue #4250.

**UPDATE**

In the meantime, I plan to publish a module (**Math::FractionalPart**) to more clearly show some options and help discussions toward the best way to proceed.

### CODE REVIEW

**Comment by lizmat** [comment]
It feels indeed like `frac` was merged too soon: I was not aware of the different definitions of `frac` and `fractional`.  I do feel there's a benefit in there being an easy way to get to the fractional part of a real value, but as to its name or *exact* semantics, I have very little to add to the discussion, I'm afraid.

**Review by vrurg — APPROVED** [review]
Same on my side, as it  is for lizmat: I had a feeling that not everything that easy with negatives.

**Comment by Altai-man** [comment]
IMO astronomical computations seem like a pretty specific field to keep something in core. What are the net benefits over just keeping a module with helpers for the field?

**Comment by lizmat** [comment]
> IMO astronomical computations seem like a pretty specific field to keep something in core

Wanting to get to the fraction of a real value, definitely is not something just being done in astronomical calculations.  :-)

**Comment by Altai-man** [comment]
>Wanting to get to the fraction of a real value, definitely is not something just being done in astronomical calculations

Fair enough, never mind me then.

**Comment by codesections** [comment]
My thoughts haven't really changed since we [first discussed](https://github.com/rakudo/rakudo/pull/4244#issuecomment-793958857) the idea of adding `frac` – I think its common/useful enough to have in core, but not common/familiar enough to justify being hufmanized down to 4 characters.

It seems like a more descriptive name would solve the ambiguities discussed upthead.  And, for someone working in a domain that uses this function, it's easy enough to add a `my &frac = &absolute-fractional-part` or whatever.  (That name is just an example, not a suggestion). 

>  tbrowder requested review from … codesections 22 hours ago 

I'm happy to review, but what does an approving review mean in the context of a reversion?  Approving the revert?  Approving the original change?  Or was it just a ping for discussion?

**Comment by lizmat** [comment]
I've merged this so that we don't have a release with potentially changed semantics on `frac`.  I'm welcoming a new PR to be discussed and possibly merged *after* the 2021.03 release.

**Comment by tbrowder** [comment]
See my revamped issue #4250 which is now my current position.

**Comment by tbrowder** [comment]
> My thoughts haven't really changed since we [first discussed](https://github.com/rakudo/rakudo/pull/4244#issuecomment-793958857) the idea of adding `frac` – I think its common/useful enough to have in core, but not common/familiar enough to justify being hufmanized down to 4 characters.
> 
> It seems like a more descriptive name would solve the ambiguities discussed upthead. And, for someone working in a domain that uses this function, it's easy enough to add a `my &frac = &absolute-fractional-part` or whatever. (That name is just an example, not a suggestion).
> 
> > tbrowder requested review from … codesections 22 hours ago
> 
> I'm happy to review, but what does an approving review mean in the context of a reversion? Approving the revert? Approving the original change? Or was it just a ping for discussion?

The latter, and, as I hoped, a reviewer (@lizmat) did as I had hoped one would do.

**Pull request merged**
