### PR TITLE
Fix List.reduce method failing with &[&&]

### PR DESCRIPTION
**Pull request by gfldex**
Tests:

```
ok (True, True, True, True).permutations».reduce(&infix:<&&>).reduce(&infix:<&&>), '.reduce with infix:<&&> returns True';
nok (True, True, True, False).permutations».reduce(&infix:<&&>).reduce(&infix:<&&>), '.reduce with infix:<&&> returns False';
my &falseish = { False };
my &trueish = { True };
nok (True, True, True, &falseish).permutations».reduce(&infix:<&&>).reduce(&infix:<&&>), '.reduce with infix:<&&> and callable returns False';
ok (True, True, True, &trueish).permutations».reduce(&infix:<&&>).reduce(&infix:<&&>), '.reduce with infix:<&&> and callable returns True';
```

### CODE REVIEW

**Comment by moon-chilled** [comment]
I fear this doesn't help with e.g. `[True, False, True].reduce(&infix:<||>)`, etc.

**Comment by gfldex** [comment]
As discussed on IRC, we want `.reduce` short circuit too.

Updated tests:

```
use v6.*;
use Test;

say (True, True, False, True).reduce(&[&&]);
say (True, True, True, True).reduce(&[&&]);
say (False, True, True, True).reduce(&[&&]);
say (True, True, True, False).reduce(&[&&]);

ok (True, True, True, True).permutations».reduce(&infix:<&&>).reduce(&infix:<&&>), '.reduce with infix:<&&> returns True';
nok (True, True, True, False).permutations».reduce(&infix:<&&>).reduce(&infix:<&&>), '.reduce with infix:<&&> returns False';
my &falseish = { False };
my &trueish = { True };
nok (True, True, True, &falseish).permutations».reduce(&infix:<&&>).reduce(&infix:<&&>), '.reduce with infix:<&&> and callable returns False';
ok (True, True, True, &trueish).permutations».reduce(&infix:<&&>).reduce(&infix:<&&>), '.reduce with infix:<&&> and callable returns True';
is ("foo" but False, "bar", "buzz").reduce(&infix:<&&>), "foo", '.reduce with infix:<&&> short circuits';

# multi sub infix:<||>(+@a)

ok (True, True, True, True).reduce(&[||]), '.reduce with infix:<||> and all True returns True';
nok (False, False, False, False).permutations».reduce(&[||]).reduce(&[&&]), '.reduce with infix:<||> and all False returns False';
ok (False, False, False, True).permutations».reduce(&[||]).reduce(&[&&]), '.reduce with infix:<||> and one True returns True';
ok (False, &trueish).reduce(&[||]), '.reduce with infix:<||> and Callable returns True';
nok (False, &falseish).reduce(&[||]), '.reduce with infix:<||> and Callable returns False';
is ("foo" but False, "bar" but False, "buzz").reduce(&infix:<||>), "buzz", '.reduce with infix:<||> short circuits';
```

**Comment by gfldex** [comment]
With the last commit, all short circuating operators work with `.reduce`. Tests for `infix:<//>` as follows.

```
is (Any, Mu, 42, Any).reduce(&[//]), 42, '.reduce with infix:<//> returns the first undefined value';
constant $undef = class :: { method defined { False } }.new;
ok (Any, Mu, $undef).reduce(&[//]) =:= $undef, '.reduce with infix:<//> returns the last alternation if no defined value is found';
```

**Review by lizmat — APPROVED** [review]

**Comment by lizmat** [comment]
I will probably do some optimizations after merge  :-)

**Pull request merged**
