### PR TITLE
Implement RT #125489

### PR DESCRIPTION
**Pull request by MasterDuke17**
Adds a .mode method to IO::[Path,Handle,Special] that returns the file's permissions as either an Int or Str.

### CODE REVIEW

**Comment by lizmat** [comment]
I like it in general, but I'm not so sure about the :Str parameter.  This sorta seems like a break from the rest.

**Comment by MasterDuke17** [comment]
What about getting rid of it and leaving just the sprintf path, but with '.Int' on the end?

**Comment by lizmat** [comment]
I'm not sure what that would give us?

**Comment by MasterDuke17** [comment]
It might just be me, but I've never in my life wanted the mode/permissions as an unmasked number (so I would argue against returning the raw value of the nqp::stat() call). But I guess I don't really have strong feelings about whether the method should return an Int or a Str.

**Comment by labster** [comment]
Why not return a Str but Int mixin?

**Comment by lizmat** [comment]
Isn't that just an IntStr ?

**Comment by MasterDuke17** [comment]
I "Cannot mix in non-composable type Int into object of type Str". I can do Int but Stringy, but I'm not sure what that buys me.
```
my int $mode = nqp::stat($!abspath, nqp::const::STAT_PLATFORM_MODE) +& 0o7777;
return new($mode, sprintf('%04o', $mode))
```
This seems nice, but Rakudo won't compile, it seems it doesn't know about IntStr at that point.

**Comment by labster** [comment]
> Isn't that just an IntStr ?

Maybe.  Let me look...
/me files perl6/doc#544

I really need to learn modern Perl 6.

**Comment by labster** [comment]
The IntStr types look OK, but you still have these signatures:

> mode(IO::Handle:D: :$Str)

**Comment by MasterDuke17** [comment]
Right, thanks for catching that.

**Comment by MasterDuke17** [comment]
Tests added in perl6/roast PR #126 (https://github.com/perl6/roast/pull/126). Documentation added in perl6/docs PR #565 (https://github.com/perl6/doc/pull/565).

**Pull request merged**
