### PR TITLE
Suggest misspelled method names

### PR DESCRIPTION
**Pull request by MasterDuke17**
Like types, lexicals, and routines/phasers, suggest methods with a
similar name if the given method is not found for the invocant.

Fixes https://rt.perl.org/Ticket/Display.html?id=123078 and
https://rt.perl.org/Ticket/Display.html?id=127395.

Passes `make m-spectest`.

### CODE REVIEW

**Comment by MasterDuke17** [comment]
@jnthn how does the most recent commit look?

**Comment by lizmat** [comment]
@MasterDuke17: I get a hang now on something like 'my ::foo $x, say $x'  Could you confirm?

**Comment by MasterDuke17** [comment]
Odd behavior. Not only did I have to add the `nqp::can` check for `methods` and `private_method_table`, but i had to change to `$!invocant`, using `$.invocant` infini-looped.

**Comment by MasterDuke17** [comment]
Rebased and merge conflicts fixed.

**Comment by zoffixznet** [comment]
Thanks.

**Pull request merged**
