### PR TITLE
Fix for RT#127402: Set.hash stringifies its objects

### PR DESCRIPTION
**Pull request by salortiz**
Now returns a parameterized Hash that reflect the Setty semantic

### CODE REVIEW

**Comment by timo** [comment]
looks good, thanks!

**Comment by salortiz** [comment]
Seen applied, and then reverted by @lizmat in 2e17820, waiting for definition on bugfixes.
BTW, the syntax my %e{Any} isn't available at this stage, so I use direct parameterization.
Should reopen?

**Comment by jnthn** [comment]
Yes, reopen. Expect to have the fix guidelines out around the start of next week.

**Comment by lizmat** [comment]
> On 30 Jan 2016, at 21:06, Salvador Ortiz <notifications@github.com> wrote:
> Seen applied, and then reverted by @lizmat in 2e17820, waiting for definition on bugfixes.
> BTW, the syntax my %e{Any} isn't available at this stage, so I use direct parameterization.

I see now.   Hmmm… I had compiled the setting with %e{Any}  (which it did, without problem), but apparently it is indeed not doing the right thing.  So Salvador, I stand corrected: your original pull request should be done once we agree on the handling of bug fixes in rakudo vis-a-vis language levels.


Salvador Ortiz++



Liz

**Pull request merged**
