### PR TITLE
Awesomify “malformed loop spec” errors

### PR DESCRIPTION
**Pull request by AlexDaniel**
This is a questionable fix for [RT #127857.](https://github.com/Raku/old-issue-tracker/issues/5220)

Makes each parse of a loop construct 0.04 ms slower. So if you have
one hundred ｢loop｣-s in your code, that's already about four
milliseconds slower.

Also breaks one 6.c-errata test that checks for “loop spec” text.

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Looking for some thoughts on how to make this PR suck less.

**Comment by AlexDaniel** [comment]
Some examples of error messages:

```perl6
loop (my $x = 0, $x < 10, $x++) {}
```
```
===SORRY!=== Error while compiling -e
Malformed loop spec (expected 3 semicolon-separated expressions but got 1)
at -e:1
------> loop (my $x = 0, $x < 10, $x++⏏) {}
```
```perl6
loop () {}
```
```
===SORRY!=== Error while compiling -e
Malformed loop spec (expected 3 semicolon-separated expressions)
at -e:1
------> loop (⏏) {}
    expecting any of:
        prefix
        term
```
```perl6
loop (my $x = 0; $x < 10; $x++;) {}
```
```
===SORRY!=== Error while compiling -e
Malformed loop spec (expected 3 semicolon-separated expressions but got more)
at -e:1
------> loop (my $x = 0; $x < 10; $x++⏏;) {}
```

**Comment by AlexDaniel** [comment]
Failing errata test in question: https://github.com/perl6/roast/blob/34577134e02213a3d303f70d307173d873699510/S32-exceptions/misc.t#L783-L784

**Comment by ugexe** [comment]
IMO all the extra code (especially in a hot path) is not worth it just to give a slightly better error message.

**Comment by AlexDaniel** [comment]
@ugexe What kind of hot path are we talking about? This is a compile-time thingy that happens once.

I see a little problem in the way it attempts to match three ‘;’-separated EXPRs. I'm thinking, why not ``$<e>=(<EXPR>?)+ % ';'``, or something like that? It would need a corresponding change in Actions file, but for some reason I couldn't really get it right this way. That said, if it did that, then maybe there'd be no overhead for the code blocks? Or something like that. I'm pretty sure there's a way to do it without introducing any performance hit.

**Comment by AlexDaniel** [comment]
FWIW I measured the performance hit by creating a file with 5000 loops.

**Comment by ugexe** [comment]
I misunderstood, thinking it applied to each iteration instead of each loop. Disregard.

**Comment by JJ** [comment]
The conflict needs to be looked at, it's not directly solvable. Can you check?

**Comment by AlexDaniel** [comment]
The conflict itself is not a big deal, this PR simply needs more work to make the change versioned.

**Comment by AlexDaniel** [comment]
Ah, oops, I mistook this for another PR. I think this one can be merged, actually. I think I even had tests for this somewhere.

**Comment by AlexDaniel** [comment]
OK, I don't have tests for this. FWIW the errata issue can be simply adjusted to test for /^loop spec/ instead.

**Comment by AlexDaniel** [comment]
> The conflict needs to be looked at, it's not directly solvable. Can you check?

```git rebase --strategy-option patience master``` did it.

**Pull request merged**
