### PR TITLE
Usage replace $*PROG-NAME with literal “command”

### PR DESCRIPTION
**Pull request by kalkin**

### CODE REVIEW

**Comment by vendethiel** [comment]
Can I ask what's the reason for this one?

**Comment by zoffixznet** [comment]
> Can I ask what's the reason for this one?

There's been a somewhat lengthy discussion on this today: https://irclog.perlgeek.de/perl6/2016-11-22#i_13613926

It boils down to basically the current version generating unreadable usage messages. Below's one generated for `zef`, for example:

```
zoffix@VirtualBox:~$ zef --blah
Usage:
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E [--force] fetch [<identities> ...] -- Download specific distributions
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E [--force] test [<paths> ...] -- Run tests
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E [--force] build [<paths> ...] -- Run Build.pm
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E [--depends] [--test-depends] [--build-depends] [--test] [--fetch] [--force] [--dry] [--update] [--upgrade] [--depsonly] [--serial] [--exclude=<Any>] [--to|--install-to=<Any>] install [<wants> ...] -- Install
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E [--force] [--from|--uninstall-from=<Any>] uninstall [<identities> ...] -- Uninstall
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E [--wrap=<Int>] search [<terms> ...] -- Get a list of possible distribution candidates for the given terms
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E [--max=<Int>] [-i|--installed] list [<at> ...] -- A list of available modules from enabled content storages
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E upgrade [<at> ...] -- Upgrade installed distributions (BETA)
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E rdepends <identity> -- View reverse dependencies of a distribution
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E [--sha1] locate <identity> -- Lookup locally installed distributions by short-name, name-path, or sha1 id
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E [--wrap=<Int>] info <identity> -- Detailed distribution information
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E [--force] look <identity> -- Download a single module and change into its directory
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E [--depends] [--test-depends] [--build-depends] [--test] [--fetch] [--force] [--update] [--upgrade] [--depsonly] [--exclude=<Any>] [--to|--install-to=<Any>] smoke -- Smoke test
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E update [<names> ...] -- Update package indexes
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E [--confirm] nuke [<names> ...] -- Nuke module installations (site, home) and storages from config (RootDir, StoreDir, TempDir)
  /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E [-h|--help] 
zoffix@VirtualBox:~$ 
```

**Comment by zoffixznet** [comment]
Based on [earlier conversation](https://irclog.perlgeek.de/perl6/2016-11-22#i_13613926) and [ascent in #perl6-dev](https://irclog.perlgeek.de/perl6-dev/2016-11-23#i_13615201), seems there's a general 👍 on this PR, so I'm merging :)

**Comment by zoffixznet** [comment]
Thanks a lot!

**Pull request merged**
