### PR TITLE
Add a $.path attribute and PF_UNIX multis to IO::Socket::INET

### PR DESCRIPTION
**Pull request by Kaiepi**
The methods and attributes of `IO::Socket::INET` are currently geared more towards IPv4/IPv6 addresses. This makes it so UNIX sockets have more appropriate methods and attributes WRT their addresses.

Passes `make test` and `make spectest`.

### CODE REVIEW

**Comment by ugexe** [comment]
Do other language implementations mix INET and UNIX? For example: perl has IO::Socket::INET and IO::Socket::UNIX

**Comment by Kaiepi** [comment]
Python's `socket`, Haskell's `Network.Socket`, .NET's `System.Net.Sockets` are some examples of modules similar to `IO::Socket::INET` that mix UNIX and IP socket support.

I see `IO::Socket::INET` as being a lower level API for working with sockets than `IO::Socket::Async`, rather than just being a synchronous API for them. Outside of how their address is handled and the socket is initialized, there isn't much difference between how UNIX and IP sockets are used when used like sockets. Combined with a solution to https://github.com/Raku/problem-solving/issues/111 (which is something I want to deal with after this, before implementing sync UDP socket support), the differing state between different families of sockets would be handled by their address, not `IO::Socket::INET` itself. The name becomes a misnomer for what it's doing though...

**Comment by Kaiepi** [comment]
With the solution for https://github.com/Raku/problem-solving/issues/111, it becomes clearer that support for UNIX sockets doesn't belong in `IO::Socket::INET`. I was hoping to eventually make this class handle all synchronous sockets as `IO::Socket::Sync`, but due to it being designed with IPv4 sockets in mind, this complicates its `listen` and `connect` methods significantly. `IO::Socket::UNIX` would be a more fitting place to handle UNIX socket support, but that needs to wait until the problem solving issue is solved.

**Comment by lizmat** [comment]
Perhaps we should be more thinking about roles in this context?

**Comment by Kaiepi** [comment]
How so? There are multiple ways they could get involved here.

**Pull request closed without merging**
