### PR TITLE
Add unicmp op which uses unicmp_s nqp op to do string compare

### PR DESCRIPTION
**Pull request by samcv**

### CODE REVIEW

**Comment by b2gills** [comment]
I don't like the name, for one the string comparison operator is `leg`.

I also don't have any ideas about what would be a good name.

**Comment by zoffixznet** [comment]
> I don't like the name, for one the string comparison operator is `leg`.

.oO( `lug` ...)

**Comment by samcv** [comment]
leg just calls cmp_s, which is the same as cmp does, and the underlying nqp op is unicmp_s

Any thoughts on better names?

**Comment by zoffixznet** [comment]
> leg just calls cmp_s, which is the same as cmp does, and the underlying nqp op is unicmp_s

But there are other `cmp` candidates for all sorts of types, whereas `leg` is just for strings.

> Any thoughts on better names?

Not really, though I find `unileg` sounding even more amusing than plain `leg` :P

**Comment by samcv** [comment]
Commited this directly and it is hidden behind `use experimental :unicmp`

https://github.com/rakudo/rakudo/commit/6f6f0cf19ed10e8c7e3e828b3a776eb2c3220fc1
https://github.com/rakudo/rakudo/commit/5870ef97d1cd7f94d578a8359a70fddbf57e9820

**Pull request closed without merging**
