### PR TITLE
Small IO cleanup

### PR DESCRIPTION
**Pull request by cygx**
Removes defunct `&pipe`, simplifies `&open`.

### CODE REVIEW

**Comment by zhuomingliang** [comment]
I'd like to see this get merged, thanks. :+1:

**Comment by lizmat** [comment]
Until we have clarity on how we're going to handle version, it would seem wise not to change / remove stuff, especially like this.  So, not going to do that right now.

**Comment by cygx** [comment]
@lizmat `&pipe` is backed by `IO::Handle.pipe` which was removed [on September 4th](https://github.com/rakudo/rakudo/commit/03b5a0abb58905f8e8e6e768186696f10e37729e#diff-836232d4364a7df1cf3ff9c1e022cf0bL34).

**Comment by lizmat** [comment]
Removed pipe() with c0bb692

**Comment by cygx** [comment]
now obsolete

**Pull request closed without merging**
