### PR TITLE
Removed capture_and_parcel and its callers

### PR DESCRIPTION
**Pull request by cognominal**

### CODE REVIEW

**Comment by lizmat** [comment]
Shouldn't we not just change the name from Parcel to List ???

**Comment by cognominal** [comment]
Yes, one must go further. I am not sure for the next one :

SIG_ELEM_IS_PARCEL should be renamed SIG_ELEM_IS_LIST or SIG_ELEM_IS_SEQ?

**Comment by lizmat** [comment]
Leaving that to jnthn

**Comment by cognominal** [comment]
Not needed anymore. TimToady pushed a better patch :
https://github.com/rakudo/rakudo/commit/e0fc14d37cac3b6be2c769db9c302148e4601714

**Pull request closed without merging**
