### PR TITLE
Show stagestats for dependent precompilation

### PR DESCRIPTION
**Pull request by timo**
This way you can get much more info when your "stage parse"
takes long, and you can more easily see the dependency
structure of your projects (though of course modules that
were already precompiled won't show up here)

here's example output:

```
Stage start      :   0.000
Stage parse      :            
precomp ../p6-Pango/lib/Pango/FontFamily.pm6
    Stage start      :   0.000
    Stage parse      :        
    precomp ../../install/share/perl6/site/sources/4E98DE0759FBF012DDC3AC7FD3BFF32B8C9E2200
        Stage start      :   0.000
        Stage parse      :   0.254
        Stage syntaxcheck:   0.000
        Stage ast        :   0.000
        Stage optimize   :   0.003
        Stage mast       :   0.011
        Stage mbc        :   0.001
    
    precomp ../p6-Pango/lib/Pango/Compat/Types.pm6
        Stage start      :   0.000
        Stage parse      : 
        precomp ../../install/share/perl6/site/sources/D96FC9ADA5EBB3DF3F47CE69DFFA5B95BFCA0A13
            Stage start      :   0.000
            Stage parse      :  10.902
            Stage syntaxcheck:   0.000
            Stage ast        :   0.000
            Stage optimize   :   0.290
            Stage mast       :   1.012
            Stage mbc        :   0.026
        
        precomp ../p6-Pango/lib/Pango/Roles/Pointers.pm6
            Stage start      :   0.000
            Stage parse      :   0.967
            Stage syntaxcheck:   0.000
            Stage ast        :   0.000
            Stage optimize   :   0.002
            Stage mast       :   0.040
            Stage mbc        :   0.001
         15.364
        Stage syntaxcheck:   0.000
        Stage ast        :   0.000
        Stage optimize   :   0.043
        Stage mast       :   0.172
        Stage mbc        :   0.005
    
    precomp ../p6-Pango/lib/Pango/Raw/Types.pm6
        Stage start      :   0.000
        Stage parse      :   1.992
        Stage syntaxcheck:   0.000
        Stage ast        :   0.000
        Stage optimize   :   0.050
        Stage mast       :   0.310
        Stage mbc        :   0.006
    
    precomp ../p6-Pango/lib/Pango/Raw/DescriptionMetrics.pm6
        Stage start      :   0.000
        Stage parse      :   3.509
        Stage syntaxcheck:   0.000
        Stage ast        :   0.000
        Stage optimize   :   0.049
        Stage mast       :   0.273
        Stage mbc        :   0.010
    
    precomp ../p6-Pango/lib/Pango/Roles/Types.pm6
        Stage start      :   0.000
        Stage parse      : 
        precomp ../p6-Pango/lib/Pango/Raw/Utils.pm6
            Stage start      :   0.000
            Stage parse      :   1.075
            Stage syntaxcheck:   0.000
            Stage ast        :   0.000
            Stage optimize   :   0.026
            Stage mast       :   0.077
            Stage mbc        :   0.003
        
        precomp ../p6-Pango/lib/Pango/Roles/Protection.pm6
            Stage start      :   0.000
            Stage parse      :   0.179
            Stage syntaxcheck:   0.000
            Stage ast        :   0.000
            Stage optimize   :   0.004
            Stage mast       :   0.008
            Stage mbc        :   0.001
          2.558
        Stage syntaxcheck:   0.000
        Stage ast        :   0.000
        Stage optimize   :   0.020
        Stage mast       :   0.061
        Stage mbc        :   0.003
     26.123
    Stage syntaxcheck:   0.000
    Stage ast        :   0.000
    Stage optimize   :   0.006
    Stage mast       :   0.057
    Stage mbc        :   0.002

precomp ../p6-GtkPlus/lib/GTK/Compat/Types.pm6
    Stage start      :   0.000
    Stage parse      : 
    precomp ../p6-GtkPlus/lib/GTK/Roles/Pointers.pm6
        Stage start      :   0.000
        Stage parse      :   0.938
        Stage syntaxcheck:   0.000
        Stage ast        :   0.000
        Stage optimize   :   0.002
        Stage mast       :   0.051
        Stage mbc        :   0.001
      6.819
    Stage syntaxcheck:   0.000
    Stage ast        :   0.000
    Stage optimize   :   0.194
    Stage mast       :   0.855
    Stage mbc        :   0.017

precomp ../p6-GtkPlus/lib/GTK/Raw/Types.pm6
    Stage start      :   0.000
    Stage parse      : 
    precomp ../p6-GtkPlus/lib/GTK/Compat/RGBA.pm6
        Stage start      :   0.000
        Stage parse      :   1.422
        Stage syntaxcheck:   0.000
        Stage ast        :   0.000
        Stage optimize   :   0.021
        Stage mast       :   0.101
        Stage mbc        :   0.003
     10.039
    Stage syntaxcheck:   0.000
    Stage ast        :   0.000
    Stage optimize   :   0.122
    Stage mast       :   1.090
    Stage mbc        :   0.014

precomp ../p6-GtkPlus/lib/GTK/Application.pm6
    Stage start      :   0.000
    Stage parse      : 
    precomp ../p6-GtkPlus/lib/GTK/Raw/Subs.pm6
        Stage start      :   0.000
        Stage parse      :   3.999
        Stage syntaxcheck:   0.000
        Stage ast        :   0.000
        Stage optimize   :   0.034
        Stage mast       :   0.194
        Stage mbc        :   0.009
    
    precomp ../p6-GtkPlus/lib/GTK/Raw/Application.pm6
        Stage start      :   0.000
        Stage parse      :   2.608
        Stage syntaxcheck:   0.000
        Stage ast        :   0.000
        Stage optimize   :   0.030
        Stage mast       :   0.152
        Stage mbc        :   0.008
    
    precomp ../p6-GtkPlus/lib/GTK/Raw/Window.pm6
        Stage start      :   0.000
        Stage parse      :  10.016
        Stage syntaxcheck:   0.000
        Stage ast        :   0.000
        Stage optimize   :   0.112
        Stage mast       :   0.459
        Stage mbc        :   0.016
    
    precomp ../p6-GtkPlus/lib/GTK/Compat/Roles/Object.pm6
        Stage start      :   0.000
        Stage parse      : 
        precomp ../p6-GtkPlus/lib/GTK/Compat/Raw/IsType.pm6
            Stage start      :   0.000
            Stage parse      :   0.965
            Stage syntaxcheck:   0.000
            Stage ast        :   0.000
            Stage optimize   :   0.007
            Stage mast       :   0.061
            Stage mbc        :   0.003
          2.214
        Stage syntaxcheck:   0.000
        Stage ast        :   0.000
        Stage optimize   :   0.010
        Stage mast       :   0.075
        Stage mbc        :   0.003
    
    precomp ../p6-GtkPlus/lib/GTK/Compat/Roles/ActionMap.pm6
        Stage start      :   0.000
        Stage parse      : 
        precomp ../p6-GtkPlus/lib/GTK/Raw/Utils.pm6
            Stage start      :   0.000
            Stage parse      :   1.345
            Stage syntaxcheck:   0.000
            Stage ast        :   0.000
            Stage optimize   :   0.035
            Stage mast       :   0.161
            Stage mbc        :   0.006
          2.956
        Stage syntaxcheck:   0.000
        Stage ast        :   0.000
        Stage optimize   :   0.015
        Stage mast       :   0.122
        Stage mbc        :   0.003
    
    precomp ../p6-GtkPlus/lib/GTK/Roles/Signals/Generic.pm6
        Stage start      :   0.000
        Stage parse      : 
        precomp ../p6-GtkPlus/lib/GTK/Raw/ReturnedValue.pm6
            Stage start      :   0.000
            Stage parse      :   0.095
            Stage syntaxcheck:   0.000
            Stage ast        :   0.000
            Stage optimize   :   0.001
            Stage mast       :   0.007
            Stage mbc        :   0.001
          6.388
        Stage syntaxcheck:   0.000
        Stage ast        :   0.000
        Stage optimize   :   0.121
        Stage mast       :   0.421
        Stage mbc        :   0.020
    
    precomp ../p6-GtkPlus/lib/GTK/Roles/Signals/Application.pm6
        Stage start      :   0.000
        Stage parse      :   1.401
        Stage syntaxcheck:   0.000
        Stage ast        :   0.000
        Stage optimize   :   0.022
        Stage mast       :   0.074
        Stage mbc        :   0.007
    
    precomp ../p6-GtkPlus/lib/GTK/ApplicationWindow.pm6
        Stage start      :   0.000
        Stage parse      : 
        precomp ../p6-GtkPlus/lib/GTK/Raw/ApplicationWindow.pm6
            Stage start      :   0.000
            Stage parse      :   1.513
            Stage syntaxcheck:   0.000
            Stage ast        :   0.000
            Stage optimize   :   0.032
            Stage mast       :   0.078
            Stage mbc        :   0.007
        
        precomp ../p6-GtkPlus/lib/GTK/Window.pm6
            Stage start      :   0.000
            Stage parse      : 
            precomp ../p6-GtkPlus/lib/GTK/Bin.pm6
                Stage start      :   0.000
                Stage parse      : 
                precomp ../p6-GtkPlus/lib/GTK/Raw/Bin.pm6
                    Stage start      :   0.000
                    Stage parse      :   1.171
                    Stage syntaxcheck:   0.000
                    Stage ast        :   0.000
                    Stage optimize   :   0.010
                    Stage mast       :   0.068
                    Stage mbc        :   0.007
                
                precomp ../p6-GtkPlus/lib/GTK/Container.pm6
                    Stage start      :   0.000
                    Stage parse      : 
                    precomp ../p6-GtkPlus/lib/GTK/Raw/Container.pm6
                        Stage start      :   0.000
                        Stage parse      :   4.175
                        Stage syntaxcheck:   0.000
                        Stage ast        :   0.000
                        Stage optimize   :   0.051
                        Stage mast       :   0.219
                        Stage mbc        :   0.008
                    
                    precomp ../p6-GtkPlus/lib/GTK/Adjustment.pm6
                        Stage start      :   0.000
                        Stage parse      : 
                        precomp ../p6-GtkPlus/lib/GTK/Raw/Adjustment.pm6
                            Stage start      :   0.000
                            Stage parse      :   2.514
                            Stage syntaxcheck:   0.000
                            Stage ast        :   0.000
                            Stage optimize   :   0.034
                            Stage mast       :   0.157
                            Stage mbc        :   0.009
                          3.949
                        Stage syntaxcheck:   0.000
                        Stage ast        :   0.000
                        Stage optimize   :   0.034
                        Stage mast       :   0.109
                        Stage mbc        :   0.010
                    
                    precomp ../p6-GtkPlus/lib/GTK/Widget.pm6
                        Stage start      :   0.000
                        Stage parse      : 
                        precomp ../p6-Pango/lib/Pango/Context.pm6
                            Stage start      :   0.000
                            Stage parse      : 
                            precomp ../p6-Pango/lib/Pango/Compat/GList.pm6
                                Stage start      :   0.000
                                Stage parse      : 
                                precomp ../p6-Pango/lib/Pango/Compat/Raw/GList.pm6
                                    Stage start      :   0.000
                                    Stage parse      :   2.130
                                    Stage syntaxcheck:   0.000
                                    Stage ast        :   0.000
                                    Stage optimize   :   0.033
                                    Stage mast       :   0.151
                                    Stage mbc        :   0.005
                                  3.568
                                Stage syntaxcheck:   0.000
                                Stage ast        :   0.000
                                Stage optimize   :   0.031
                                Stage mast       :   0.131
                                Stage mbc        :   0.004
                            
                            precomp ../p6-Pango/lib/Pango/Raw/Context.pm6
                                Stage start      :   0.000
                                Stage parse      :   2.133
                                Stage syntaxcheck:   0.000
                                Stage ast        :   0.000
                                Stage optimize   :   0.025
                                Stage mast       :   0.163
                                Stage mbc        :   0.005
                            
                            precomp ../p6-Pango/lib/Pango/Roles/References.pm6
                                Stage start      :   0.000
                                Stage parse      :   1.092
                                Stage syntaxcheck:   0.000
                                Stage ast        :   0.000
                                Stage optimize   :   0.005
                                Stage mast       :   0.049
                                Stage mbc        :   0.002
                            
                            precomp ../p6-Pango/lib/Pango/FontMetrics.pm6
                                Stage start      :   0.000
                                Stage parse      :   0.992
                                Stage syntaxcheck:   0.000
                                Stage ast        :   0.000
                                Stage optimize   :   0.010
                                Stage mast       :   0.058
                                Stage mbc        :   0.003
                              9.676
                            Stage syntaxcheck:   0.000
                            Stage ast        :   0.000
                            Stage optimize   :   0.026
                            Stage mast       :   0.104
                            Stage mbc        :   0.004
[hundreds of lines snipped]                        
502.357
Stage syntaxcheck:   0.000
Stage ast        :   0.000
Stage optimize   :   0.029
Stage mast       :   0.107
Stage mbc        :   0.015
Stage moar       :   0.000
```

### CODE REVIEW

**Comment by lizmat** [comment]
Would be nice if the `Stage parse: ` would not be shown until **after** a nested precomp is done.  So that instead of this:

    Stage start      :   0.000
    Stage parse      :        
    precomp ../../install/share/perl6/site/sources/4E98DE0759FBF012DDC3AC7FD3BFF32B8C9E2200
        Stage start      :   0.000
        Stage parse      :   0.254
       ...
    0.516

It would show:

    Stage start      :   0.000
    precomp ../../install/share/perl6/site/sources/4E98DE0759FBF012DDC3AC7FD3BFF32B8C9E2200
        Stage start      :   0.000
        Stage parse      :   0.254
       ...
    Stage parse      :  0.516

**Comment by timo** [comment]
would it be fine it it just did that for all stages, or maybe it would always output the "Stage parse" after it's done and the others stay the way they are now. I don't see a good way to output "Stage parse" only if there won't be precomp, but if we're outputting to a terminal on linux, we can at least erase the line back to the beginning before we print something out …

I think the sanest approach is to move the "stage blah" output to the end along with the time it outputs

**Comment by timo** [comment]
btw this hasn't gone in yet because somehow the rakudo part of the patch breaks reproducible builds, and i haven't investigated yet how that happens.

**Comment by JJ** [comment]
@timo also, conflicts. Can you please check?

**Comment by lizmat** [comment]
Is this PR still salvageable?

**Pull request closed without merging**
