### PR TITLE
Try harder to diagnose problem instead of reporting undeclared type

### PR DESCRIPTION
**Pull request by usev6**
Fixes RT #125902

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Can we have this rebased to resolve the conflict? Ping @usev6

**Comment by usev6** [comment]
I'll test my changes with current nom and push an updated version.

**Comment by AlexDaniel** [comment]
I see no problem with this PR. It may be over-engineered as you say, but it gives awesome error messages. I was able to reproduce all of them:

```perl6
my Str where ‘foo’ $test;
```
```
===SORRY!=== Error while compiling -e
Malformed my (found type followed by constraint; did you forget a variable in between?)
at -e:1
------> my Str ⏏where ‘foo’ $test;
```

```perl6
my Int is default(42)
```
```
===SORRY!=== Error while compiling -e
Malformed my (found type followed by trait; did you forget a variable in between?)
at -e:1
------> my Int ⏏is default(42)
```

```perl6
my Str;
```
```
===SORRY!=== Error while compiling -e
Malformed my (did you forget a variable after type?)
at -e:1
------> my Str⏏;
```

Without this PR it simply says “malformed my” which is arguably LTA. Spectest clean, merging.

**Comment by jonathanstowe** [comment]
:+1:

**Pull request merged**
