### PR TITLE
Issue 1588: Populate Signal enum with getsignals op

### PR DESCRIPTION
**Pull request by jstuder-gh**
Previously, Rakudo and it's backends used system-independent signal
values and transformed them to the proper value when submitting a signal
handler. However when used in conjunction with NativeCall and the native
C kill implementation, the fact that the Signal values do not match the
host system becomes a problem.

Making it so that the signal numbers exposed to the user as Signal enums
will match those of their host system. They can be set via the
getsignals op, which will retrieve the valid signals from the host.

See <https://github.com/rakudo/rakudo/issues/1588>

### CODE REVIEW

**Comment by jstuder-gh** [comment]
Relies on PRs <https://github.com/MoarVM/MoarVM/pull/814> and <https://github.com/perl6/nqp/pull/430>

**Comment by jstuder-gh** [comment]
Now that the [MoarVM component](https://github.com/MoarVM/MoarVM/pull/814) of this development has been reviewed and merged, requesting a merge of the related [NQP PR](https://github.com/perl6/nqp/pull/430) and this. Doing so will expose the mapped signums to P6 users via the Signal enum, addressing [Issue 1588](https://github.com/rakudo/rakudo/issues/1588). Thanks.

**Comment by jstuder-gh** [comment]
@lizmat, I noticed that my NQP PR regarding signals was merged. That PR removes the NQP signal constants (as they are no longer accurate), which is causing the errors seen on Rakudo. Please merge in this PR and that should stop the errors (in addition to setting all the Signal enum values :+1: )

**Comment by lizmat** [comment]
And bumped, rakudo is green again

**Pull request merged**
