### PR TITLE
Rewrite `for ^10 + 1` into a while loop

### PR DESCRIPTION
**Pull request by MasterDuke17**
The existing optimization to turn `for ^10` into a while loop doesn't
work if an offset is being added. Currently only adding an offset is
supported, but subtraction and multiplication could be added at the cost
of additional complexity.

Rakudo builds ok and passes `make m-test m-spectest`.

`Nil for ^10_000_000 + 1` took ~1.3s before, and ~.9s after.

### CODE REVIEW

**Comment by MasterDuke17** [comment]
To be more explicit, it's `Nil for (^10_000_000) + 1`, which currently after optimization is not converted into a while loop. After this PR, it would be converted into a while loop.

**Comment by MasterDuke17** [comment]
It would require folding into the starting value and then changing the op from `prefix:<^>` to `infix:<..>`. As far as I know the only optimization that might come close is what was originally done (by you IIRC) in https://github.com/rakudo/rakudo/blob/master/src/Perl6/Optimizer.nqp#L1112-L1126. But that just re-writes the various ops into while loops and doesn't do the `Nil for (^10_000_000) + 1 ` case because the condition https://github.com/rakudo/rakudo/blob/master/src/Perl6/Optimizer.nqp#L1119 fails because `$theop.name` is `&infix:<+>`.

**Comment by lizmat** [comment]
My point is that this PR is the wrong approach: it should not be needed for this case, because the expression `^10_000_000 + 1" should have been folded already, probably into `1..^10_000_001`.  That `for` will then be handled by the existing code.

**Comment by MasterDuke17** [comment]
Hm, I kind of thought that that since this optimization happens so soon in visit_op https://github.com/rakudo/rakudo/blob/master/src/Perl6/Optimizer.nqp#L1101-L1114, there wouldn't be a chance for the constant folding to occur.

**Comment by MasterDuke17** [comment]
So you're suggesting essentially pulling my ifelse branch out into an if before https://github.com/rakudo/rakudo/blob/master/src/Perl6/Optimizer.nqp#L1114 ?

**Comment by lizmat** [comment]
I'm saying that **an** optimization should optimize `(^10) + 1)` to `1..^11` *before* we consider the `for` optimization,

**Comment by MasterDuke17** [comment]
Oh, I just started a v2 that re-writes `(^10) + 1` to `1..^11`, but realized that'll miss non-literal cases. With this PR, `my $a = 2; Nil for ^10 + $a` is re-written into a while loop:
```
              - QAST::Stmt <sunk final> .say for (^4) + $a
                - QAST::Want <sunk> :statement_level<?> :statement_id<2>
                  - QAST::Op(stmts) <sunk> :IterationEnd<?> .say for (^4) + $a
                    - QAST::Stmts 
                      - QAST::Op(bind) 
                        - QAST::Var(local range_it__1 :decl(var)) 
                        - QAST::Op(sub_i) 
                          - QAST::Var(lexicalref $a) <wanted> $a
                          - QAST::IVal(1) 
                      - QAST::Op(bind) 
                        - QAST::Var(local range_max__1 :decl(var)) 
                        - QAST::Op(add_i) 
                          - QAST::Var(lexicalref $a) <wanted> $a
                          - QAST::IVal(3) 
                      - QAST::Op(bind) 
                        - QAST::Var(local range_callee__1 :decl(var)) 
                        - QAST::Op(p6capturelex)  :past_block<?> :code_object<?>
                          - QAST::Op(callmethod clone) 
                            - QAST::WVal(Block :cuid(1))  :past_block<?> :code_object<?>
                      - QAST::Op(while) 
                        - QAST::Op(isle_i) 
                          - QAST::Op(bind) 
                            - QAST::Var(local range_it__1) 
                            - QAST::Op(add_i) 
                              - QAST::Var(local range_it__1) 
                              - QAST::IVal(1) 
                          - QAST::Var(local range_max__1) 
                        - QAST::Op(call) 
                          - QAST::Var(local range_callee__1) 
                          - QAST::Var(local range_it__1) 
                      - QAST::WVal(Nil) 
                  - v
                  - QAST::Op(p6sink) <sunk>
                    - QAST::Op(stmts) <sunk> :IterationEnd<?> .say for (^4) + $a
                      - QAST::Stmts 
                        - QAST::Op(bind) 
                          - QAST::Var(local range_it__1 :decl(var)) 
                          - QAST::Op(sub_i) 
                            - QAST::Var(lexicalref $a) <wanted> $a
                            - QAST::IVal(1) 
                        - QAST::Op(bind) 
                          - QAST::Var(local range_max__1 :decl(var)) 
                          - QAST::Op(add_i) 
                            - QAST::Var(lexicalref $a) <wanted> $a
                            - QAST::IVal(3) 
                        - QAST::Op(bind) 
                          - QAST::Var(local range_callee__1 :decl(var)) 
                          - QAST::Op(p6capturelex)  :past_block<?> :code_object<?>
                            - QAST::Op(callmethod clone) 
                              - QAST::WVal(Block :cuid(1))  :past_block<?> :code_object<?>
                        - QAST::Op(while) 
                          - QAST::Op(isle_i) 
                            - QAST::Op(bind) 
                              - QAST::Var(local range_it__1) 
                              - QAST::Op(add_i) 
                                - QAST::Var(local range_it__1) 
                                - QAST::IVal(1) 
                            - QAST::Var(local range_max__1) 
                          - QAST::Op(call) 
                            - QAST::Var(local range_callee__1) 
                            - QAST::Var(local range_it__1) 
                        - QAST::WVal(Nil) 
```
However, if instead it was first re-written into `my $a = 2; Nil for (0 + $a)..^(10 + $a)`, then the current optimization won't apply:
```
            - QAST::Stmts <sunk> my int $a = 2; .say for (0+$a)..^(4+$a)
              - QAST::Stmt <sunk> my int $a = 2
                - QAST::Op(assign_i)  :statement_id<1>
                  - QAST::Var(lexicalref $a) <wanted sinkok> $a
                  - QAST::Want <wanted> 2
                    - QAST::WVal(Int) 
                    - Ii
                    - QAST::IVal(2)  2
              - QAST::Stmt <sunk final> .say for (0+$a)..^(4+$a)
                - QAST::Want <sunk> :statement_level<?> :statement_id<2>
                  - QAST::Op(p6forstmt) <sunk> :IterationEnd<?> .say for (0+$a)..^(4+$a)
                    - QAST::Op(callstatic &infix:<..^>) <wanted> ..^
                      - QAST::Stmts  +
                        - QAST::Stmt <wanted final>
                          - QAST::Op(add_i) 
                            - QAST::Want <wanted> 0
                              - QAST::WVal(Int) 
                              - Ii
                              - QAST::IVal(0)  0
                            - QAST::Var(lexicalref $a) <wanted> $a
                      - QAST::Stmts  +
                        - QAST::Stmt <wanted final>
                          - QAST::Op(add_i) 
                            - QAST::Want <wanted> 4
                              - QAST::WVal(Int) 
                              - Ii
                              - QAST::IVal(4)  4
                            - QAST::Var(lexicalref $a) <wanted> $a
                    - QAST::Op(p6capturelex)  :past_block<?> :code_object<?>
                      - QAST::Op(callmethod clone) 
                        - QAST::WVal(Block :cuid(1))  :past_block<?> :code_object<?>
                  - v
                  - QAST::Op(p6sink) <sunk>
                    - QAST::Op(p6forstmt) <sunk> :IterationEnd<?> .say for (0+$a)..^(4+$a)
                      - QAST::Op(callstatic &infix:<..^>) <wanted> ..^
                        - QAST::Stmts  +
                          - QAST::Stmt <wanted final>
                            - QAST::Op(add_i) 
                              - QAST::Want <wanted> 0
                                - QAST::WVal(Int) 
                                - Ii
                                - QAST::IVal(0)  0
                              - QAST::Var(lexicalref $a) <wanted> $a
                        - QAST::Stmts  +
                          - QAST::Stmt <wanted final>
                            - QAST::Op(add_i) 
                              - QAST::Want <wanted> 4
                                - QAST::WVal(Int) 
                                - Ii
                                - QAST::IVal(4)  4
                              - QAST::Var(lexicalref $a) <wanted> $a
                      - QAST::Op(p6capturelex)  :past_block<?> :code_object<?>
                        - QAST::Op(callmethod clone) 
                          - QAST::WVal(Block :cuid(1))  :past_block<?> :code_object<?>
```

**Comment by lizmat** [comment]
Am about to be on the road until tonight, and then will need all the time to get the P6W out of the door.  So don’t expect much from me until tomorrow

**Comment by MasterDuke17** [comment]
No hurry, it's a minor optimization.

**Comment by lizmat** [comment]
Still mulling over this one.

**Comment by TisonKun** [comment]
expect `my $a = 2; Nil for (0 + $a)..^(10 + $a)` to be first applied constant propagation and then folded, into `Nil for 2..^12` and finally be optimized as while loop. If is exactly `Nil` there, in aggressive optimize, even ignore the whole stmt.

**Comment by AlexDaniel** [comment]
Let's please not. It's a lot of complexity for a rarely used feature.

**Comment by AlexDaniel** [comment]
FWIW it is still noticeably slower:
* https://gist.github.com/61fd9fb1060883ab1400f5ba5f8fdc07
* vs
* https://gist.github.com/beb90de373a1b07fcace353e83f928f0

**Pull request closed without merging**
