### PR TITLE
Add named argument :initial-elems to Blob.new

### PR DESCRIPTION
**Pull request by salortiz**
Create an allocated, empty (zeroed) Blob of the given size.
Works also with Buf and subclases.

### CODE REVIEW

**Comment by jnthn** [comment]
+1 to the idea, though I think -1 to :elems(...). With shaped arrays we called it :shape(...) instead, and while a multi-dimensional Buf doesn't really make sense, it makes sense to use the same API if we're going to actually *fix* the size (though that'll need a more extensive patch to use the MultiDimArray REPR instead). Furthermore, that'd mean you could simply say:

    my @a[1024] is Buf;

If the idea is to initialize it with a certain number of elements but then allow resizing, then I'd rather go with something that's a bit more explicit about that.

**Comment by salortiz** [comment]
@jnthn, thanks for the comment.

I don't use `:shape` because I don't want to *fix* the size, only pre-allocate some slots so:

`Blob.new:100elems.elems == 100`

**Comment by ugexe** [comment]
You can pre-allocate pretty nicely this way too: `Blob.new: 0 xx 5`

**Comment by salortiz** [comment]
Yes @ugexe, but the difference in speed is really big:
Blob.new(0 xx 10000) vs Blob.new(:initial-elems(10000)) -> 200.2908/s  vs 38052.1614/s

**Comment by salortiz** [comment]
And with FSA enabled in MoarVM even bigger: 200.9773/s vs 58411.0240/s!

**Comment by salortiz** [comment]
With lizmat++ Blob.allocation this can be closed.

**Pull request closed without merging**
