### PR TITLE
Travis CI: build on Ubuntu 14.04 instead of 12.04 and use GCC 6

### PR DESCRIPTION
**Pull request by samcv**
This pull request is ready to be merged if it is wanted.

### CODE REVIEW

**Comment by samcv** [comment]
This is now complete. Does anybody have any opinion on this at all?

**Comment by samcv** [comment]
I was mostly wondering if the flapping native call test could stop flapping if we make this change, and we can always go back to it if the test stops flapping (we will know there is some difference).

https://irclog.perlgeek.de/perl6-dev/2016-12-24#i_13792601

**Comment by zoffixznet** [comment]
Thanks.

**Comment by ugexe** [comment]
Seems wrong to change the language from perl to java just to keep from uncommenting the line to install the jdk (which should only be needed for the nvm anyway?)

**Comment by samcv** [comment]
@ugexe if that isn't changed on the Travis CI 14.04 it doesn't have javac in the path at the moment, which is why it was changed. I would have just installed it if it were that simple.

If there is another way to specify the javac path *easily* let me know

**Comment by ugexe** [comment]
I assume thats because you tried `openjdk-7-jre` when you really wanted `openjdk-7-jdk`

**Comment by ugexe** [comment]
@samcv ^ ?

**Pull request merged**
