### PR TITLE
Perl6-architecture

### PR DESCRIPTION
**Pull request by ccworld1000**
Perl6-architecture

### CODE REVIEW

**Comment by zoffixznet** [comment]
Don't know if there was a discussion elsewhere about this, but what is this? Also, should the linked SVG be part of rakudo's repo (and link changed) rather than a third-party repo being used?

**Comment by ugexe** [comment]
Looks like something that would need to be generated automatically with a git hook, similar to how p6doc has to generate the type graphs.

**Comment by AlexDaniel** [comment]
As for diagramming, ping @JJ :)

**Comment by JJ** [comment]
I just adjusted a bit the current diagram, with your help... I can help some if needed...

**Comment by ccworld1000** [comment]
Q:"These are not classes, so I don't think they should be on the diagram:"
A:Sorry, note information is displayed, I will deal with it right away.

@AlexDaniel

**Comment by ccworld1000** [comment]
that's OK!
[https://github.com/ccworld1000/CCArchitecture](https://github.com/ccworld1000/CCArchitecture)

**Comment by AlexDaniel** [comment]
@ccworld1000 what about code?

**Pull request closed without merging**
