### PR TITLE
Add CI job that runs a spectest instead of Rakudo tests

### PR DESCRIPTION
**Pull request by MasterDuke17**

### CODE REVIEW

**Comment by vrurg** [comment]
_Instead_? It doesn't look right to me.

**Comment by MasterDuke17** [comment]
> _Instead_? It doesn't look right to me.

It's correct. This one new job doesn't run Rakudo tests and uses the time saved to run a spectest. It doesn't mean any changes to the other jobs, they all continue to run Rakudo tests.

**Review by niner — APPROVED** [review]
Worth a try!

**Review by vrurg — APPROVED** [review]
Ok, let's give it a try. I always wanted specs to be ran too.

**Pull request merged**
