### PR TITLE
Simplify Supply / whenever processing order

### PR DESCRIPTION
**Pull request by patrickbkr**
Previously whenevers tapped their connected supply instantly. To prevent deadlocks caused by loops back to the supply block the awaiter was overwritten to take a continuation whenever a lock was awaited, snipping off the stack up to the latest whenever. Those continuations were then put in a list and run one after the other. This logic can work around all sorts of locking scenarios, but is difficult to predict and can still manage to deadlock in some cases. In addition this changed awaiter also triggered for locks not part of the supply / whenever setup. So external unrelated locks could affect the order of how the code is executed. That made the code even more difficult to predict.

This patch removes all of that functionality. Instead whenevers now never do their tap instantly, but always do it after the supply (or whenever) code block containing the whenever has finished. That way the supply block lock is released before the tapping happens that could potentially also want the supplies lock, circumventing a lot of deadlock potential.

As the new behavior does not at all try to solve deadlocks by reordering execution order it is possible there are situations where the previous lock solver would have resolved a situation, where the new logic deadlocks. I do not know if there are any such practical cases.

Solves #5141

### CODE REVIEW

**Comment by patrickbkr** [comment]
I have just tried running a `make test` and a `make spectest` with this. There are several legitimately failing tests.
This needs more work. I'll see if I can turn this into somewhere useful.

**Comment by patrickbkr** [comment]
I have now changed `done` to only be run after the whenevers have been processed. That gets a lot more tests to succeed.

Now I'm stumped on the following test from `t/spec/S17-promise/nonblocking-await.t`:

    my $kill = Promise.new;
    my $started = Promise.new;
    my $s-address = '0.0.0.0';
    my $c-address = '127.0.0.1';
    my $port = 4893;
    my $ok = start react {
        whenever IO::Socket::Async.listen($s-address, $port) -> $conn {
            whenever $conn.Supply(:bin) -> $buf {
                await $conn.write: $buf;
                $conn.close;
            }
        }
        whenever $kill { done }
        $started.keep;
    }

    await $started;
    my @responses;
    for ^20 {
        react {
            whenever IO::Socket::Async.connect($c-address, $port) -> $client {
                await $client.write('is this thing on?'.encode('ascii'));
                whenever $client.Supply(:bin) {
                    push @responses, .decode('ascii');
                    $client.close;
                }
            }
        }
    }
    $kill.keep;
    lives-ok { await $ok }, 'Server survived';
    ok @responses == 20, 'Got 20 responses from async socket server that does non-blocking await';
    is @responses[0], 'is this thing on?', 'First response correct';
    ok [eq](@responses), 'Rest of responses also correct';

Note the `$started.keep` at the end of the first react block. With this PR it runs before the whenevers are processed and thus cause the connection to not be set up yet. With the new semantics this can't be made work reliably.

But: This kind of code isn't reliable with the current whenever implementation either, because the BlockAddWheneverAwaiters reorder the code when awaits happen, so it's possible for the same problem to occur, just not reliably.

I'm unsure how to proceed.

**Comment by vrurg** [comment]
I would say if you know a better logic for syncing states then just implement it. As long as the test logic takes care of  non-blocking `await` on sockets implementation details are irrelevant.

**Comment by patrickbkr** [comment]
@vrurg: This issue has nothing to do with sockets. Consider:

```
my $s = supply {
    say "processing whenever"
}
react {
    whenever $s { }
    say "end of react block";
}
```
With this PR that code prints
```
end of react block
processing whenever
```
That's the issue I have. The reason this happens is that with this PR whenevers are always only processed *after* the code in the supply block finished running.

Now consider:

```
my $p = Promise.new;
my $s1 = supply {
    await $p;
    say "processing whenever"
};
react {
    whenever $s1 { }
    say "end of react block";
    $p.keep;
}
```

That code prints, both with *and without* this PR:
```
end of react block
processing whenever
```

So the previous implementation isn't immune to this problem either. It just works out most of the time.

What happens on the previous implementation? When - during the processing of a whenever block - an await happens (be it a `protect`, `acquire`, `lock` or plain `await`) a continuation starting at the root of the `whenever` is taken. Only after the supply block itself finished running the continuation is resumed. So the order in which the code is executed is dependent on whether there is any locking going on in code tapped by the whenever.

I really don't have a good idea how this could be resolved.

I don't like the previous implementation as it's a bit unpredictable and fails in corner cases. (See above and https://github.com/rakudo/rakudo/issues/5141)
I don't like this PR because it's unexpected that whenevers are  processed *after* the supply block finished, the syntax indicates otherwise.

**Comment by patrickbkr** [comment]
Closing in favor of #5202.

**Pull request closed without merging**
