### PR TITLE
Fix RT #118223

### PR DESCRIPTION
**Pull request by MasterDuke17**

### CODE REVIEW

**Comment by MasterDuke17** [comment]
FYI, this passes spectest.

**Comment by zoffixznet** [comment]
I'm wondering if there's a solution that doesn't involve `quietly`. It has quite a large cost:

```
zoffix@leliana:/tmp/tmp.CZjRUmBket$ time perl6 -e 'my $x; $x++ for ^1000_000'

real	0m0.779s
user	0m0.740s
sys	0m0.033s
zoffix@leliana:/tmp/tmp.CZjRUmBket$ time perl6 -e 'my $x; quietly $x++ for ^1000_000'

real	0m2.002s
user	0m1.917s
sys	0m0.077s
zoffix@leliana:/tmp/tmp.CZjRUmBket$ 
```

**Comment by zoffixznet** [comment]
I stand corrected. It was a poor test:

```
zoffix@leliana:/tmp/tmp.OIrpsuxlLS$ time perl6 -e 'my @keys = ^10000; my @res = @keys Z=> @keys;'

real	0m0.939s
user	0m0.887s
sys	0m0.050s
zoffix@leliana:/tmp/tmp.OIrpsuxlLS$ time perl6 -e 'my @keys = ^10000; my @res = quietly @keys Z=> @keys;'

real	0m0.953s
user	0m0.880s
sys	0m0.070s
zoffix@leliana:/tmp/tmp.OIrpsuxlLS$ 
```

Also, there's probably isn't a better way, since we can't just filter undefineds, because we don't know what op we're using.

**Comment by AlexDaniel** [comment]
100 commits, huh? Oops ;)

**Comment by MasterDuke17** [comment]
Shit

**Pull request merged**
