### PR TITLE
Colon lists

### PR DESCRIPTION
**Pull request by skids**

### CODE REVIEW

**Comment by skids** [comment]
The relevant portions of the spec are:

S02:

```
All of the adverbial forms (including the normal ones with identifier keys)
are considered special tokens and are recognized in various positions in
addition to term position.  In particular, when used where an infix would be
expected they modify the previous topmost operator that is tighter in
precedence than "loose unary"
```

...and this section can get a bit confusing about exactly what it is each
phrase is referring to.

```
Two or more adverbs can always be strung together without intervening
punctuation anywhere a single adverb is acceptable.  When used as named
arguments in an argument list, you I<may> put comma between, because they're
just ordinary named arguments to the function, and a fatarrow pair would
work the same.  However, this comma is allowed only when the first pair
occurs where a term is expected.  Where an infix operator is expected, the
adverb is always taken as modifying the nearest preceding operator that is
not hidden within parentheses, and if you string together multiple such
pairs, you may not put commas between, since that would cause subsequent
pairs to look like terms.  (The fatarrow form is not allowed at all in
operator position.) See S06 for the use of adverbs as named arguments.
```

...so I tried to get the behavior that seemed to be what made sense
and was more or less what the existing code seemed to be trying to do,
except adding it also inside `[]` and fixing QAST problems with `:a<...>`.

Note that one unconventional thing done in this patch is calling
QAST::Node.named(NQPNull) when converting WVals to Pair contructors,
since there is no way to remove a SpecialArg role.  Not sure of
the propreity of that.

Anyway, hopefully this behavior makes sense.

Current behavior without this patch:

```
 (:g :h, :f :i; :j :k).perl.say; # :i(1) and a useless-use warning
 (:j(42) :h<foo>).perl.say       # Unknown QAST type NQPMu
 [1, :a:b].perl.say              # [1, :a]
```

With this patch:

```
 (:g :h, :f :i; :j :k).perl.say;  # ((:g, :h, :f, :i), (:j, :k))
 (:j(42) :h<foo>).perl.say        # (:j(42), :h("foo"))
 [1, :a:b].perl.say               # [1, :a, :b]
```

**Comment by patzim** [comment]
I tried this out on latest master and got the following error during stage parse:

`Stage parse      : Cannot find method 'method_order' on object of type NQPConcreteRoleHOW
   at gen/moar/Metamodel.nqp:2955  (blib/Perl6/Metamodel.moarvm:apply)
 from gen/moar/Metamodel.nqp:3227  (blib/Perl6/Metamodel.moarvm:compose)
 from src/Perl6/World.nqp:3228  (blib/Perl6/World.moarvm:)
 from src/Perl6/World.nqp:5289  (blib/Perl6/World.moarvm:)
 from src/Perl6/World.nqp:5285  (blib/Perl6/World.moarvm:ex-handle)
 from src/Perl6/World.nqp:3225  (blib/Perl6/World.moarvm:pkg_compose)
 from gen/moar/Perl6-Actions.nqp:3158  (blib/Perl6/Actions.moarvm:package_def)
 from gen/moar/stage2/QRegex.nqp:1598  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/QRegex.moarvm:!cursor_pass)
 from gen/moar/Perl6-Grammar.nqp:2174  (blib/Perl6/Grammar.moarvm:package_def)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:package_declarator:sym<class>)
 from gen/moar/stage2/QRegex.nqp:1697  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:package_declarator)
 from gen/moar/Perl6-Grammar.nqp:2254  (blib/Perl6/Grammar.moarvm:scoped)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:scope_declarator:sym<my>)
 from gen/moar/stage2/QRegex.nqp:1697  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:term:sym<scope_declarator>)
 from gen/moar/stage2/QRegex.nqp:1697  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from gen/moar/Perl6-Grammar.nqp:3639  (blib/Perl6/Grammar.moarvm:termish)
 from gen/moar/stage2/NQPHLL.nqp:1041  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from gen/moar/Perl6-Grammar.nqp:3675  (blib/Perl6/Grammar.moarvm:EXPR)
 from gen/moar/Perl6-Grammar.nqp:956  (blib/Perl6/Grammar.moarvm:statement)
 from gen/moar/Perl6-Grammar.nqp:884  (blib/Perl6/Grammar.moarvm:statementlist)
 from gen/moar/stage2/NQPHLL.nqp:1263  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/NQPHLL.moarvm:LANG)
 from gen/moar/Perl6-Grammar.nqp:1320  (blib/Perl6/Grammar.moarvm:FOREIGN_LANG)
 from gen/moar/Perl6-Grammar.nqp:826  (blib/Perl6/Grammar.moarvm:comp_unit)
 from gen/moar/Perl6-Grammar.nqp:555  (blib/Perl6/Grammar.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:2302  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:2078  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/NQPHLL.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:1998  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:2031  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:2023  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:2018  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1714  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1936  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:1896  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:38  (blib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1821  (/home/patrick/p6-repos/rakudo/../install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:95  (perl6.moarvm:MAIN)
 from gen/moar/main.nqp:60  (perl6.moarvm:<mainline>)
 from <unknown>:1  (perl6.moarvm:<main>)
 from <unknown>:1  (perl6.moarvm:<entry>)
make: *** [Makefile:527: CORE.setting.moarvm] Error 1`

**Comment by skids** [comment]
Hrm weird... but the auto-checks passed.  I'll try a fresh checkout from 79a1d22 and see if that error can be replicated here.

**Comment by patzim** [comment]
Working over here now too. I probably messed up with git before.

**Comment by skids** [comment]
Good.  Thanks for freshening the PR!

**Comment by skids** [comment]
Issues and RTs to review if/when this is merged: 

RT#127267, RT#126209, RT#127023, #1500, #2863, #2536 and the three RTs mentioned therein.

In the case of RT#124553 this is not a problem with colon lists, but rather a problem specific to some (perhaps dubious, perhaps intentionally added post-synopses) treatment of the capture composer term introducer as a prefix:<\> operator which takes adverbs... though I cannot find any reference to prefix:<\> being an operator in specs or docs, it seems this works in normal lists.  The test is dubious in either case: current behavior is, the function gets a single positional argument containing a capture... an alternative behavior would be a "You can't adverb \(:foo)" since that is what happens with (1, :a), it being a colon list started where an infix is expected, which is forbidden).

**Comment by MasterDuke17** [comment]
Just a nitpick, but there are a mix of styles used in the new code. Sometimes conditionals and loops have "superstition" parens (e.g., `if (foo) {}` instead of `if foo {}`), which generally aren't used in "core" NQP/Rakudo.

**Comment by skids** [comment]
Heheh.  Old Perl5 habits die hard, I'm afraid.  I can address this and any other nitpicks but I'll wait a bit to see more if they come first.

**Comment by lizmat** [comment]
@skids: Am about to merge... will take care of any style issues after that, ok

**Comment by skids** [comment]
Thanks lizmat!

**Comment by lizmat** [comment]
Thank you, for persevering  :-)

**Pull request merged**
