### PR TITLE
Throw an X::Syntax on nameless postfix .::  (Fix for RT#130181)

### PR DESCRIPTION
**Pull request by skids**

### CODE REVIEW

**Comment by skids** [comment]
tests are in my roast branch of the same name.  I'll push those once this is merged.

**Comment by lizmat** [comment]
I'm slightly worried about parsing performance for what would essentially be an extra check for every method call.  Do you have any idea on that?

**Comment by skids** [comment]
I only compiled a couple of times so I can't offer statistically significant numbers.  stage stats didn't go outside their normal range.  Trying to finesse LTM to get the block to run only if it chose a literal '::' over <longname> is a bit beyond my rx-foo.

**Comment by vendethiel** [comment]
Would adding a leading `| '::' { ... }` be enough, or not?

**Comment by vendethiel** [comment]
A literal always win to a subrule (that has no literals, even) in LTM, iirc

**Comment by skids** [comment]
Right but you *do* want to match the longname in case the '::' is followed by something.  And you *don't* want the block to run if that happens.  I think (?) is there is a '::' {} rule above longname the {} will get run when it first tries to match just the '::', even though it eventually chooses the longname

Now if we added
  <?before '::'> <longname> {}

...above the <logname> I think that would safely only run the code for all cases where the identifier starts with ::, which is rare.

**Comment by vendethiel** [comment]
Thanks for the precision

**Pull request merged**
