### PR TITLE
Make attribute defaults typecheck work at run-time too.

### PR DESCRIPTION
**Pull request by vrurg**
Follow-up to #3452.

This PR turns on `create_BUILDPLAN` typechecking on attribute defaults for run-time. If a type is created by user code dynamically, any type mismatch could be detected as early as `compose` is called.

### CODE REVIEW

**Comment by vrurg** [comment]
Not really sure how much sense does it really make though. It looks like a safeguard code to me anyway.

I thought mixins would be affected as they're run-time things, but quick tests didn't come up with any situation where the code would throw at run time. On the other hand, while testing I clearly seen `t/spec/S14-roles/parameterized-basic.t` failing because `nqp::gethllsym` was returning a wrong symbol due to a bug. So, I conclude that there're situations in the wild when typechecking happens after compunit parsing is done and `$*W` cannot be used. So I think this PR should make sense.

**Comment by lizmat** [comment]
will look at this later tonight or tomorrow

**Comment by lizmat** [comment]
Ok, I've looked at this PR several times now, and I fail to see how this would actually add runtime attribute typechecks.  Since  none of this affects the BUILDPLAN unrolling in Perl6/World.nqp.  So am I missing something?  Could you come up with a piece of code that fails now, and would not fail with this PR???

**Comment by vrurg** [comment]
Closing because I also haven't found any case where this PR would work. At some point I was getting weird rakudo compilation errors while receiving incorrect typeobjects from `gethllsym`, but those was probably caused by something else.

Thanks, @lizmat!

**Pull request closed without merging**
