### PR TITLE
Match infix eqv

### PR DESCRIPTION
**Pull request by Xliff**
infix:<eqv> implementation for Match objects.

### CODE REVIEW

**Comment by lizmat** [comment]
although .to/.from/,orig are easy to check, I'm not sure whether they should be part of eqv for Matches

Also, to short-circuit Matches eqvied with themselves, a very cheap a =:= b might be in order

**Comment by Xliff** [comment]
@lizmat, you are correct, I had the identity check in an earlier version but it was lost and I forgot to include it in the re-implementation. I will add that back in, now. Thanks for the reminder.

in your opinion, what should be part of eqv for Matches?

**Comment by lizmat** [comment]
Feels to me this should be more about *what* is matched, not *where* it was matched?

**Comment by moritz** [comment]
@lizmat I disagree. `eqv` is a pretty strict comparison. If you an distinguish two objects by looking at their attributes or their `.perl` output, they shouldn't be equivalent.

**Comment by moritz** [comment]
Thanks @Xliff, squash-merged.

**Pull request merged**
