### PR TITLE
Update 2021.04.md

### PR DESCRIPTION
**Pull request by k-mx**
Missed backticks and fixed url

### CODE REVIEW

**Comment by Altai-man** [comment]
Thanks!

Does it conflict with suggestion in https://github.com/rakudo/rakudo/issues/4314 ?

**Comment by k-mx** [comment]
Yes. I better undo url changes and keep only backticks. Okay?

**Comment by Altai-man** [comment]
This will be very good.

**Review by Altai-man — APPROVED** [review]

**Comment by Altai-man** [comment]
Merged, I also updated the release description. Thanks a lot for your contribution!

**Pull request merged**
