### PR TITLE
Fix .slurp-rest(:!bin)

### PR DESCRIPTION
**Pull request by ugexe**

### CODE REVIEW

**Comment by lizmat** [comment]
Good catch!

ugexe: is there a reason why you added the :$bin in the second candidate?

**Comment by ugexe** [comment]
So `:!bin` is not treated as an unexpected named parameter

**Comment by lizmat** [comment]
ugexe: but that is only for subs, not methods.  Unexpected named parameters disappear into thin air.

**Comment by lizmat** [comment]
in any case, adding a "where" clause in a signature generally slows down things a lot, so I'm coming up with another solution

**Pull request merged**
