### PR TITLE
Fix for GH #1852: pod converts non-breaking space into normal space

### PR DESCRIPTION
**Pull request by tbrowder**
Tests have been added for the fix.

### CODE REVIEW

**Comment by lizmat** [comment]
Thanks!

**Comment by tbrowder** [comment]
Thanks, lizmat, for speedy review and merge.

**Comment by JJ** [comment]
Did this make it into the 2018.5 release?

**Comment by AlexDaniel** [comment]
No.

**Comment by JJ** [comment]
Any idea of if it will make it to the next one?

**Comment by lizmat** [comment]
Yes.  It’s in master now, afaik

**Comment by AlexDaniel** [comment]
Yes.

**Pull request merged**
