### PR TITLE
Separate adding child block from creating code obj

### PR DESCRIPTION
**Pull request by jstuder-gh**
Not a necessary change, but one that I think make things a bit clearer.

Previously, the create_simple_code_object method in the Perl6 World
would add the block passed to it to the desired outer block in addition
to returning a code object for it. From the name, it is not clear that
the method has such side-effects. Separating the actions in order to
make it explicit that we performing both of these.

### CODE REVIEW

**Comment by jstuder-gh** [comment]
Also wanted to point out that at [line 8338 in Actions](https://github.com/jstuder-gh/rakudo/blob/sep_code_obj_actions/src/Perl6/Actions.nqp#L8338) it is pushing the block onto the outer block twice.

I didn't change that as I don't know the full context of what is going on there, but it does look a bit suspect IMO.

**Comment by zoffixznet** [comment]
👎 on this. We can probably just tweak the original name for clarity. I don't see much point in paying for another lookup of `$*W` variable plus another method call just because original method name doesn't tell the full story.

**Comment by vendethiel** [comment]
> paying for another lookup of $*W variable

Is the cost that high? Would it make sense to alias it in a local variable beforehand, then?

**Comment by jstuder-gh** [comment]
Ok, I see your point. Added another commit that changes the name instead and hopefully makes it a bit more clear that the method performs additional actions.

**Comment by zoffixznet** [comment]
👍 Thanks!

**Comment by zoffixznet** [comment]
> Also wanted to point out that at line 8338 in Actions it is pushing the block onto the outer block twice.

> I didn't change that as I don't know the full context of what is going on there, but it does look a bit suspect IMO.

Yeah, that looks to be a bug and it should be pushed only once. Looking at the [QAST dump](https://temp.perl6.party/s-qast.html) of `my $x ~~ s/foo/bar/` `QAST::Block :cuid(2)` shows up twice.

**Pull request merged**
