### PR TITLE
Refactor NativeCall CStr

### LINKED ISSUE #2633: Using explicitly-manage with NativeCall strings is impossible
## The Problem
See title. Also, `explicitly-manage` returns a `CStr` when it should probably be returning a `Str` instead.

## Expected Behavior
You should be able to use `explicitly-manage` with strings passed to native subs.

## Actual Behavior
Calling the native sub with the string `explicitly-manage` has been used on throws a type error.

## Steps to Reproduce

```
<Kaiepi> m: use NativeCall; sub strlen(Str --> size_t) is native {*}; sub free(Pointer[void]) is native {*}; my Str $foo = explicitly-manage('ayy lmao'); say strlen($foo); free(nativecast(Pointer[void], $foo))
<camelia> rakudo-moar 5b231e099: OUTPUT: «Type check failed in assignment to $foo; expected Str but got NativeCall::CStr (NativeCall::CStr.new)␤  in block <unit> at <tmp> line 1␤␤»
<Kaiepi> m: use NativeCall; sub strlen(Str --> size_t) is native {*}; sub free(Pointer[void]) is native {*}; my Str $foo = 'ayy lmao'; explicitly-manage($foo); say strlen($foo); free(nativecast(Pointer[void], $foo))
<camelia> rakudo-moar 5b231e099: OUTPUT: «8␤Native call expected return type with CPointer, CStruct, CArray, or VMArray representation, but got a P6opaque (Str+{NativeCall::ExplicitlyManagedString})␤  in sub nativecast at /home/camelia/rakudo-m-inst-2/share/perl6/sources/947BDAB9F96E0E5FC…»
```

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.4 GENERIC.MP#364 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.12-246-g5b231e099 built on MoarVM version 2018.12-36-g34fac5f4e
implementing Perl 6.d.

### PR DESCRIPTION
**Pull request by Kaiepi**
Fixes #2633

### CODE REVIEW

**Comment by lizmat** [comment]
Not sure if we should merge this before or after the release.  Otherwise +1 (with my limited knowledge of NativeCall)

**Comment by Kaiepi** [comment]
My bad, `explicitly-manage` is supposed to be returning a `CStr`, not a `Str`. I changed it so `CStr` is exported so users can use it as a type though

**Comment by JJ** [comment]
Unfortunately, it's conflicting now. Can you please check?

**Comment by lizmat** [comment]
Is this still salvageable, or did it bitrot beyond repair after new-disp landed, and @niner did a lot of work in this area?

**Pull request closed without merging**
