### PR TITLE
Add warnings on improper use of .contains and .index

### PR DESCRIPTION
**Pull request by lizmat**
As part of the discussion in #4098.  Spectest clean.

### CODE REVIEW

**Comment by raiph** [comment]
Is `index` as a sub delegating to method form? If so, then great, if not,, then there's that.

**Comment by lizmat** [comment]
It does.

**Comment by raiph** [comment]
Does it make sense to at least consider having default implementations for `contains` and `index` in the `Iterable` role that produce a simple generic warning?

I say this because, while I see [Zoffix's point about retaining `contains` and `index` for non-Str objects that respond to a `.Str` coercion by producing a scalar string rendering that works fine for `contains` and `index` such as `Match` objects and `IO::Path` objects](https://github.com/rakudo/rakudo/pull/907#issuecomment-256741597) (I presume he's right about the latter), it seems to me that using `contains` or `index` on any `Iterable` is asking for trouble.

**Comment by raiph** [comment]
Strawman proposed generic warnings for inclusion in `contains` and `index` methods in `Iterable`:

        my $name := self.^name;
        warn "Applying '.contains' to a $name will look at its .Str representation.".naive-word-wrapper;

        my $name := self.^name;
        warn "Applying '.index' to a $name will look at its .Str representation.".naive-word-wrapper;

**Comment by lizmat** [comment]
I think we still need the discussion on whether we should do these warnings (which I'm in favour of) and for which methods: today on #raku, someone was using `.comb` on an array of arrays.  Same for `split` I guess.  And `starts-with`, `ends-with`, `eqat` etc.

**Comment by lizmat** [comment]
Perhaps the subs / methods in question could take a `:quietly` parameter to indicate that you know what you're doing?

**Comment by patrickbkr** [comment]
Wouldn't `.Str' do the same and be clearer about what's happening?

**Comment by lizmat** [comment]
@patrickbkr good point.  Ok, scratch the `:quietly` idea :-)

**Pull request merged**
