### PR TITLE
Make TimToady happy

### PR DESCRIPTION
**Pull request by AlexDaniel**
https://irclog.perlgeek.de/perl6/2017-02-27#i_14175119

### CODE REVIEW

**Comment by zoffixznet** [comment]
👎 from me. One's an Easter Egg. Two's a bloat.

**Comment by AlexDaniel** [comment]
Woah, woah! Let's not jump to conclusions!

**Comment by lizmat** [comment]
Agree with Zoffix.  Also, without the comma *is* the canonical version by Douglas Adams.

**Comment by zoffixznet** [comment]
Closing this. I'm sure we can make TimToady happy by submitting fixes to [real bugs](https://perl6.fail/) instead :smile_cat:

**Pull request closed without merging**
