### PR TITLE
Add "ask" as an alias to "prompt" in 6.e

### PR DESCRIPTION
**Pull request by lizmat**
In response to https://github.com/rakudo/rakudo/issues/5022

FWIW, I'm tending to not support this PR myself.  I just created it so that everybody knows what would be needed to make this happen.  And to make sure it is opt-in for users of 6.e.

### CODE REVIEW

**Comment by Altai-man** [comment]
With all the respect to your time, -1 on actually merging this.

**Comment by lizmat** [comment]
@Altai-man making the PR was about 3 mins, no worries if this doesn't get merged :-)

**Comment by vrurg** [comment]
I don't see a need in this too.

**Comment by fluca1978** [comment]
IMHO this is a bad idea: why having two routines that do the same things without any difference? This can make difficult to document and remember in future applications.

**Comment by melezhik** [comment]
> IMHO this is a bad idea: why having two routines that do the same things without any difference? This can make difficult to document and remember in future applications.

maybe because someone might think that "ask" is better name ...

**Comment by Altai-man** [comment]
>maybe because someone might think that "ask" is a better name ...

Someone might also think that "ask" is a worse name, then what?

Raku is maybe one of the most customizable languages out here, so people are free to modify it how it fits them, but locally. There is just no need to make the change available universally for the whole community, making the CORE fatter, introducing more and more new things unless they fix clear bugs.

**Comment by Altai-man** [comment]
Look at how other languages estimate what should go into core/spec - a thing is introduced as a module and then gets widely adopted, so widely that thousands and thousands of devs are relying on it for years, proving it's actually _useful_ to them.

While the scale of the Raku community is a lot smaller, the same sort of approach is probably making sense here to - one can release a package with "better defaults" and see what's the degree of adoption it'll have. My estimate is most people don't really care about names that much, it's a very tiny nuance, how buggy or stable or fast or easy to adopt is much more important, but given it proves to be true - it should probably be adopted regardless of what I think.

More of that, we're always facing a pile of grains sort of problem - at what point a couple of grains turns into a huge pile if you add them one by one? Sure 1 or 2 or even 10 aliases won't hurt, but at what point will it turn into a huge thing you need a reference to work with on a daily basis?

Given we're adding this, we should probably think of some policy for a process of addition.

**Comment by 2colours** [comment]
Is this PR still needed? It seems to me that this isn't actually going to get merged and the supplementary [Ask module](https://raku.land/zef:tbrowder/Ask) can be a long-term solution.

**Pull request closed without merging**
