### PR TITLE
give the user a way to disable perl5 warnings (only one so far)

### PR DESCRIPTION
**Pull request by timo**
when writing 

```
no warnings :p5;
```

you can get rid of the warning that numbers starting with 0 are not parsed as octals.

I'd like to get some feedback; Especially what else to change. Maybe I should have a look at the P6Regex grammar/actions for more things?

### CODE REVIEW

**Comment by lizmat** [comment]
Now that we have lexical pragma's, this can be done easier.  One approach to this was taken by cf65f5463fc12043b00

**Comment by AlexDaniel** [comment]
Hey @zoffixznet, what do you think about this? Maybe we should start doing this more, and then it'll be easy to flip the default so that you'd need to `use warnings :p5` if you're coming from perl 5.

**Comment by zoffixznet** [comment]
> Hey @zoffixznet, what do you think about this? 

Most of the things are errors not warnings and include langs other than Perl 5.

As I've said before, these don't belong in core and should be ecosystem slang modules designed for converts from specific languages. Then they can be both more targeted and more extensive.

**Comment by AlexDaniel** [comment]
Actually, we do have something for that nowe. @lizmat, what do you think?

**Comment by timo** [comment]
i would say the "use isms" mechanism implements the idea behind this PR.

**Pull request closed without merging**
