### PR TITLE
Added proto to plan multi as suggested.

### PR DESCRIPTION
**Pull request by manwar**
Hi Team Perl6,

Please review the PR (my first one) to address the following issue:
https://github.com/rakudo/rakudo/issues/1866

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by zoffixznet** [comment]
That was fast! :smile: 

Does that fix the problem in the Issue? Like, this code should produce an error, saying you've used wrong arg:

```
$ ./perl6 -Ilib -MTest -e 'use Test; plan :skip<No widgets> if $*ENV<WIDGETS>; plan 1; ok 1'
Parameter '$skip-all' of routine 'plan' must be an object instance of type 'Cool', not a type object of type 'Cool'.  Did you forget a '.new'?
  in block <unit> at -e line 1
```

You can [build and run the spectest with Z-Script](https://rakudo.party/post/Newcomer-Guide-to-Contributing-to-Core-Perl-6#buildingstuff)

**Comment by manwar** [comment]
@zoffixznet I don't have Perl6 environment setup unfortunately.
I followed your suggestion to set ZScript but apparently I am missing something here:

manwar@ubuntu:~/zscript$ zef --depsonly install .
No command 'zef' found, did you mean:
 Command 'zf' from package 'zend-framework-bin' (universe)
 Command 'zec' from package 'zec' (universe)
 Command 'zmf' from package 'zoneminder' (universe)
zef: command not found
manwar@ubuntu:~/zscript$

**Comment by zoffixznet** [comment]
> I am missing something here

Ah, yeah, it needs a working Perl 6 installation to function :)

**Comment by manwar** [comment]
Any suggestion How to setup Perl6 environment quickly?

**Comment by zoffixznet** [comment]
```bash
mkdir ~/rakudo && cd $_
curl -LJO https://rakudo.org/latest/rakudo/source
tar -xvzf rakudo-*.tar.gz
cd rakudo-*

perl Configure.pl --backend=moar --gen-moar
make
make install

echo "export PATH=$(pwd)/install/bin/:$(pwd)/install/share/perl6/site/bin:\$PATH" \
    >> ~/.bashrc
source ~/.bashrc

cd /tmp/ &&
git clone https://github.com/ugexe/zef.git &&
cd zef &&
perl6 -Ilib bin/zef install .
```

**Comment by zoffixznet** [comment]
```bash
git clone https://github.com/rakudo/rakudo/ ~/rakudo
cd ~/rakudo

git checkout 2018.07

perl Configure.pl --backend=moar --gen-moar
make
make install

echo "export PATH=$(pwd)/install/bin/:$(pwd)/install/share/perl6/site/bin:\$PATH" \
    >> ~/.bashrc
source ~/.bashrc

cd /tmp/ &&
git clone https://github.com/ugexe/zef.git &&
cd zef &&
perl6 -Ilib bin/zef install .
```

**Comment by manwar** [comment]
manwar@ubuntu:~/rakudo$ git checkout 2018.07
error: pathspec '2018.07' did not match any file(s) known to git.
manwar@ubuntu:~/rakudo$

**Comment by zoffixznet** [comment]
My bad. That part should be `2017.06`

**Comment by manwar** [comment]
Or should it be "2018.06"?

**Comment by manwar** [comment]
Having installed "zef" as below:

    manwar@ubuntu:/tmp$ git clone https://github.com/ugexe/zef.git   
    Cloning into 'zef'...
    remote: Counting objects: 9484, done.
    remote: Compressing objects: 100% (46/46), done.
    remote: Total 9484 (delta 28), reused 30 (delta 14), pack-reused 9424
    Receiving objects: 100% (9484/9484), 1.72 MiB | 715.00 KiB/s, done.
    Resolving deltas: 100% (5821/5821), done.
    Checking connectivity... done.
    manwar@ubuntu:/tmp$ cd zef/
    manwar@ubuntu:/tmp/zef$ perl6 -Ilib bin/zef install .
    ===> Testing: zef:ver<0.4.6>:auth<github:ugexe>
    ===> Testing [OK] for zef:ver<0.4.6>:auth<github:ugexe>
    ===> Installing: zef:ver<0.4.6>:auth<github:ugexe>

    1 bin/ script [zef] installed to:
    /home/manwar/.perl6/bin
    manwar@ubuntu:/tmp$ 

Now when I try to install zscript as below, I am getting this error:

    manwar@ubuntu:~/zscript$ zef --depsonly install .
    No command 'zef' found, did you mean:
    Command 'zmf' from package 'zoneminder' (universe)
    Command 'zf' from package 'zend-framework-bin' (universe)
    Command 'zec' from package 'zec' (universe)
    zef: command not found
    manwar@ubuntu:~/zscript$

So I tried the following instead, which did the trick:

    manwar@ubuntu:~/zscript$ /tmp/zef/bin/zef --depsonly install .
    ===> Searching for missing dependencies: Config::JSON, Temp::Path
    ===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6- 
    ecosystems/master/cpan1.json
    ===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects1.json
    ===> Searching for missing dependencies: JSON::Fast, Testo, Test::When, Digest::SHA, 
    File::Directory::Tree, Test::META
    ===> Searching for missing dependencies: META6, URI
    ===> Searching for missing dependencies: JSON::Class
    ===> Searching for missing dependencies: JSON::Marshal, JSON::Unmarshal
    ===> Searching for missing dependencies: JSON::Name
    ===> Testing: JSON::Fast:ver<0.9.11>

After that I went into the checkout branch of "rakudo" and tried this:

     manwar@ubuntu:~/github/rakudo$ z --help
     z: command not found

**Comment by zoffixznet** [comment]
FWIW, if you remove the `proto` keywords you added and instead add this code before the `plan` candidates, it'll fix the bug:

```perl6
proto sub plan ($, Cool:D :$skip-all) {*}
```

You can just commit that instead of trying to fix your Perl 6 installation :)

--------------

> 1 bin/ script [zef] installed to:
> /home/manwar/.perl6/bin

That's really weird, because I don't even have `~/.perl6/bin`. And when I install zef it tells me:

```
1 bin/ script [zef] installed to:
/home/zoffix/rakudo/install/share/perl6/site/bin
```

Is your `$PATH` set up right? The instructions install rakudo to `~/rakudo`, but yours is in `~/github/rakudo`. Was similar change to the line that changes PATH done?

If you join the IRC chat, someone will be able to help: https://perl6.org/irc

**Comment by b2gills** [comment]
I'm going to take the opportunity to use this as a teaching moment.

`proto` and `multi` can't be done at the same time. Also any `proto` definition must come before any (separate) `multi` definition.

That is because a `proto` declares that there will be some number of `multi`s, it also declares the widest possible input and output. (For an anything goes `proto` use `(|)` as the signature)

Also a `proto` must have `{*}` (unless you are doing something extraordinary)

``` perl6
proto sub foo ( Numeric $? ) {*} # optional Numeric parameter

multi sub foo ( Int ) { # Int does Numeric
}
multi sub foo ( Num ) { # Num does Numeric
}
multi sub foo (     ) { # no parameter (the reason the param was marked optional)
}
```

**Comment by lizmat** [comment]
Thank you, and sorry for the delay in merging!

**Pull request merged**
