### PR TITLE
Parallelize feed operators and support lazy lists

### PR DESCRIPTION
**Pull request by Kaiepi**
This brings feed operators (`==>` and `<==` at least) more in line with the spec.

Passes `make test`, fails `make spectest` since one of its tests expects trying to use lazy lists with feed operators to throw.

### CODE REVIEW

**Comment by Kaiepi** [comment]
There's a problem with this... this benches slower than the current implementation of feed operators, even when there's blocking I/O going on at the same time. I think more discussion needs to be made about whether or not this should be implemented.

**Comment by vrurg** [comment]
Have you tried to simulate same process in a test? I mean without operator implementation, just chain a bunch of workers together and see what happens?

**Comment by Kaiepi** [comment]
Do you mean something like this?
```perl6
sub run-no-operators {
    my Channel $c .= new;
    $c.send: (1..100);
    await (
        { map { $_ ** 2 }, $_ },
        { grep { $_ %% 2 }, $_ },
        { reverse $_ },
        { sort $_ }
    ).map({
        start $c.send: $_($c.receive)
    });
    my @ = $c.receive;
}
```
If so, it runs slightly faster than with feed operators, but is still slower than before. If not, what do you mean?

**Comment by Kaiepi** [comment]
Turns out getting this to run faster was just a matter of handling QAST better. Feed operators now run roughly 500% faster than the current implementation.

**Comment by Kaiepi** [comment]
So I tinkered around with the optimizer trying to get the values of variables that can't be accessed from actions. `$*W.compile_time_evaluate` panics when I try to use it from there, which was what I was depending on for my last attempt at optimizing this to work. I can't think of any other ways to optimize this so it's faster than the current implementation.

**Comment by Kaiepi** [comment]
I changed the way I parallelize feed operators to my first attempt at implementing them. It may be slightly slower than the current implementation, but hopefully once more work is done on `Channel` they will be more performant.

**Comment by Kaiepi** [comment]
Now's probably not the best time for this with upcoming RakuAST stuff. Besides, this isn't a very good implementation.

**Pull request closed without merging**
