### PR TITLE
Correct param name with signature constraint (fixes rt#132209)

### PR DESCRIPTION
**Pull request by skids**

### CODE REVIEW

**Comment by skids** [comment]
Tests may be pulled from https://github.com/skids/roast/tree/rt132209

**Comment by lizmat** [comment]
I was looking at resolving the conflict, but I am unsure how to solve it.  @JJ maybe you have a better idea?

**Comment by JJ** [comment]
Will try to have a look...

**Comment by lizmat** [comment]
This appears to have been effectively implemented by e9a0b18c6c, so closing

**Pull request closed without merging**
