### PR TITLE
add native int version of pow

### PR DESCRIPTION
**Pull request by zhuomingliang**

### CODE REVIEW

**Comment by lizmat** [comment]
commit does not build, so vote to reject

**Comment by moritz** [comment]
Probably needs an NQP version bump

**Comment by zhuomingliang** [comment]
@lizmat it needs an NQP version bump :)

**Comment by zhuomingliang** [comment]
@lizmat now it builds. :)

**Comment by FROGGS** [comment]
Yes, I had rerun the travis build...

**Pull request merged**
