### PR TITLE
RT#129363: duckmap preserve structure types

### PR DESCRIPTION
**Pull request by cpin**
Implements `deepmap` and `duckmap` in terms of slight modification to the existing `deepmap` code.

Corresponding changes to perl6/roast made in that repo (perl6/roast#180)

Comments welcome!

### CODE REVIEW

**Comment by lizmat** [comment]
is coremap supposed to be a public method?  If not, could you rework it as a private method?

**Comment by cpin** [comment]
No, it need not be public. Will update.

**Comment by cpin** [comment]
I may be being dim here, but I don't seem to be able to see a way (easily) to make `coremap` "hidden" from the rest of the setting whilst maintaining the "bare" use of `deepmap` and `duckmap`? Lizmat made the very helpful suggestion of using a private method - difficulty being a method of _what_? :) I may be misunderstanding (very probable!)

Looking through the rest of the setting, all other "implementation detail" type subs are contained within classes which it makes sense to instantiate (such as `DateTime` for example). Admittedly, I lack the perl6 chops to really appreciate all of my options - feel free to set me straight!

**Comment by zoffixznet** [comment]
> Lizmat made the very helpful suggestion of using a private method - difficulty being a method of what? :) 

I think it would be of Rakudo::Internals: https://github.com/rakudo/rakudo/blob/nom/src/core/Rakudo/Internals.pm

> Looking through the rest of the setting, all other "implementation detail" type subs are contained within classes

I think the plan is to eventually move all of that stuff into Rakudo::Internals

**Comment by zoffixznet** [comment]
Thanks a lot!

**Pull request merged**
