### PR TITLE
Uses DISTRO when available, refs #2190

### PR DESCRIPTION
**Pull request by JJ**

### CODE REVIEW

**Comment by zoffixznet** [comment]
Looking at the [list of other occurances of `R::I`](https://github.com/rakudo/rakudo/issues/2190#issuecomment-411311721) that would still remain, is there a point in changing this one?

The new version is 11x slower (which, granted, in this case doesn't matter much) and adds shelling out to `lsb_release`/`uname` to fetch info we're not interested in.

If the original Issue remains unresolved, is there a point in increasing complexity here?

**Comment by JJ** [comment]
First, thanks for taking the time to consider this. I'll try to address your concerns.
@lizmat I'm changing an undocumented function by a stable and documented one. See also #1941 , which was rejected, so no waiting until it's documented. #1941 also makes one just guess what the two functions are all about (or at least the one which is not documented). In absence of documentation, my hunch is that I should use the documented function when available, such as in this case. 
@zoffixznet see above for your first question. In other cases where R::I still remains, `$*DISTRO` has not been registered yet so it's unavailable. 
WRT speed, you are probable comparing `$*DISTRO.is-win` witn `R::I::IS-WIN`. That's another error that I intend to address, see #2190. Although it would make a priori sense to have two different sources for truth for Windowsness (I don't know, in a cross-compiling environment, for instance), it probably makes much more sense to use the same code for both. I was expecting this issue to be accepted (or rejected) to work on that. In this particular case, the code is being called only once when the class is created. I don't think that's going to have any significant impact, even if the call itself is 11x slower.

**Comment by niner** [comment]
I still don't understand what problem this PR is supposed to fix. The change is to rakudo's core code. That's exactly the place that Rakudo::Internals is there for. IOW I don't see an issue with using Rakudo::Internals in rakudo's internals.

I've worked really hard over the years to make module loading as fast as possible. I would rather not give up any of the performance advantage when our user's don't gain anything in return. It's hard enough as it is to make this code faster while keeping it somewhat readable.

**Comment by JJ** [comment]
[`$*DISTRO.is-win` is also used in the core](https://github.com/rakudo/rakudo/blob/7c08ba7443af98cc5def12780379cf076cbb6337/src/core/REPL.pm6#L47)
Are you implying that `$*DISTRO` should be used only in user-facing code such as tests?
If this PR is intended to fix something is the absence of a guideline of when to use `$*DISTRO` or `R::I` within Rakudo. My hunch by looking at the code (which, as per #1941, is the only documentation available) was that `$*DISTRO` should be used if available. I'm OK with "*never* use `$*DISTRO` in the core", as above.

**Comment by ugexe** [comment]
No one is implying "$*DISTRO should be used only in user-facing code", or saying "never use $*DISTRO in the core". Instead lets flip this the other way -- are you stating that all rakudo code must be refactored such that there is no duplication despite any benefits the duplication may bring?

It seems like you are trying to codify how rakudo's internal code should be written, but I posit that it is more beneficial to give developers with specialized knowledge in specific areas the freedom to make an educated choice with a given context -- after all we don't state "you must write hot loops using nqp in core", "rakudo should be written in as much perl6 as possible despite performance", or similar.

**Comment by JJ** [comment]
This probably should be closed.

**Pull request closed without merging**
