### PR TITLE
add tests for #2965

### PR DESCRIPTION
**Pull request by kazcw**
This will segfault until it's built on MoarVM/MoarVM#1116

### CODE REVIEW

**Comment by kazcw** [comment]
Rebased to rerun CI now that the fix is in Moar.

**Comment by kazcw** [comment]
The tests with `--gen-moar=master` are now passing, except for [a problem with nmake in AppVeyor?](https://ci.appveyor.com/project/rakudo/rakudo/builds/25152301/job/b13vxaykxil985i3)

**Comment by ugexe** [comment]
I reran the appveyor test, and master is now failing on `t\04-nativecall\04-pointers.t`. Not sure if its related or not.

**Comment by vrurg** [comment]
`04-pointers.t` fails for quite some time now. It is not related to nmake issue, that's for sure.

As to nmake, look weird. As if `nmake` printed something different from it's version information. I would guess it failed in some way and ended with an error message.

**Comment by ugexe** [comment]
@vrurg I get failures every single time I run that test on windows. This does not happen on `2019.03.1` so something is definitely broken.

**Pull request merged**
