### PR TITLE
Implement metmodel transparency of nominalizables

### PR DESCRIPTION
**Pull request by vrurg**
As a matter of fact, a nominalizable is a wrapper around a nominal or another nominalizable. As such, it makes sense to have their MOP classes transparent, similar to how their typeobjects are transparent down to the final nominal type. I.e., it means that for

    role R[::T] {
        my subset RS of T;
        method foo(RS() $v) {...}
    }

`RS().HOW.archetypes.generic` should be true at the compile time because `RS` wraps a generic. Similarly, `RS` would have it's `coercive` archetype set would it be declared as `my subset RS of T()`. The transparency lets the compiler and runtime to make sure no nominalization is missed no matter how deep they're nested into each other. In particular, it makes the sample above possible in theory. Though in practice implementing it is yet too complicated task impractical in the light of the upcoming RakuAST implementation.

A new metmodel role `Perl6::Metamodel::Nominalizable` is introduced which provides basic common functionality of nominalizables. In particular, it implements `.^wrappee` method which allows to fetch necessary nominalization from the nesting. `RS.^wrappee(:coercion)` would return `T()` for the latter `RS` example. Correspondingly, `RS().^wrappee(:subset)` would result in `RS` itself.

Implemented `instantiate_generic` for `Metamodel::SubsetHOW`.

Implemented partial support of the new transparency in `Actions.nqp`.

Improved the performance of the new binding code by replacing a call to `coercive` method on a parameter object with `nqp::getattr` and `nqp::bitand_i` pair. For now this is all I can squeeze of it until `nqp::curcode` can be made inlinable.

### CODE REVIEW

**Comment by vrurg** [comment]
Yet, this draft currently passes spectests.

**Comment by Altai-man** [comment]
Given the current situation we likely want to get some design-wise & performance-wise review before merging.

**Comment by vrurg** [comment]
It turns out that supporting generics as subset refinees is way more complicated than expected if we aim at proper support of them everywhere. `where` blocks of a lexically scoped subset within a role declaration seemingly share same closure, to begin with. It results in the generic type used in such a `where` block resolving to a wrong typeobject. Usually to the one used with the latest role specialization.

Hopefully, this would be easier to implement with RakuAST some day.

**Comment by vrurg** [comment]
Fixes #2446 anyway.

**Pull request merged**
