### PR TITLE
Add flag for creating symlinks without absolute path

### PR DESCRIPTION
**Pull request by mienaikage**
As `.absolute` is called on the path when `.symlink` is called, it is not currently possible to create a relative symlink using this method. The added `:literal` flag is intended to allow for the altering of this behavior, creating a symlink pointing to the path as it was given.

### CODE REVIEW

**Comment by lizmat** [comment]
Looks good from functionality point of view.  But why the choice for the name `literal`?  Wouldn't `relative` make more sense?

**Comment by mienaikage** [comment]
I chose `literal` over `relative` as it allows you to specify a path without alteration, which may or may not be relative. `relative` seemed less descriptive to me for what is actually happening.

**Comment by lizmat** [comment]
Ok, well, maybe a `:$absolute = True` flag would be more appropriate, which would be True by default, and you could indicate *not* calling absolute on the path with `:!absolute`.

**Comment by mienaikage** [comment]
That does make sense, it was one of the options I had considered! (naming things is hard!)

**Comment by lizmat** [comment]
Yeah.  FWIW, this feels very strange to me, being usually at the other end of this stick  :-)

I hope some other people will chime in!

**Comment by tbrowder** [comment]
I like @lizmat's suggestion.

**Comment by AlexDaniel** [comment]
So, ideally, how should it behave? I understand that there's a backcompat concern, but it's hard to judge if a particular kludge is actually the best we can do right now if an actual solution is not defined. For example, is named parameter better than an explicit call to `.absolute`? Is one default behavior better (less unexpected?) than the other?

**Comment by lizmat** [comment]
Removing the call to `.absolute` on the inside of the `symlink` method would break code.

Adding a `:$absolute = True` named, would not.

> particular kludge

This is not a kludge, this is an addition to the existing API.  And a decent discussion about it.

**Comment by AlexDaniel** [comment]
>  And a decent discussion about it.

I agree, and discussing what would be the best API would've been a great addition. As I've said, I understand that there is a backcompat concern, I get it. Doing “additions” to the API just because a wrong default was chosen in the past is also OK, but it doesn't hurt to stop and think what would've been the best solution because perhaps there's a way to get there.

**Comment by mienaikage** [comment]
This seemed like the most appropriate solution to maintain backwards compatibility, but admittedly its current default behavior was not what I was expecting. I'd attempted to use `symlink` in the past, and forgotten why I had opted not to use it until I tried it again earlier today.

**Review by lizmat — APPROVED** [review]

**Comment by lizmat** [comment]
@mienaikage Would be nice if you could add some tests for it as well, probably in t/spec/S32-io/io-path-symlink.t .

**Comment by mienaikage** [comment]
@lizmat I shall look into putting some tests/docs together shortly.

**Pull request merged**
