### PR TITLE
[WIP] Warn if attribute accessor cannot be installed

### PR DESCRIPTION
**Pull request by vrurg**
Only compile time for now.

A solution for #3382

### CODE REVIEW

**Comment by jnthn** [comment]
This is wrong; it's a feature that you can declare something `has $.foo` and then provide a custom accessor. The use of the `.` sigil isn't just accessor generation; it's also gives a different initialization and destructuring semantics.

**Comment by lizmat** [comment]
@jnthn but this is not about that?  This is about a *method* in a role preventing the creation of an accessor method for a public attribute in a class consuming that role.  See https://github.com/rakudo/rakudo/issues/3382

**Comment by jnthn** [comment]
@lizmat Yeah; I've proposed a cleaner solution to that on the issue. I worry this one will have false positives in other cases, and isn't really solving the actual issue. :-)

**Comment by vrurg** [comment]
Agree to @jnthn. I had a spare hour to try this one out, but it's not the right approach.

Dropping away...

**Pull request closed without merging**
