### PR TITLE
Give a hint about missing provides in a META6.json when module isn't …

### LINKED ISSUE #3787: Cannot load modules from a directory which contains a META6.json without a provides key indicating the location of files.
Don't know if this is intentional behavior or not, but nobody on IRC at the time could answer that, and at the least it felt a bit spooky to me.

$ mkdir foo
$ cd foo
$ echo '{"name":""}' > META6.json # without valid JSON content rakudo throws an error, and without a defined name it throws a warning
$ touch Foo.rakumod

$ raku --ll-exception -I. -e 'use Foo; say "success";'
Could not find Foo in:
    file#/home/x/data/projects/raku/Inline-Lua-test/foo
    inst#/home/x/.raku
    inst#/home/x/.rakubrew/versions/moar-blead/install/share/perl6/site
    inst#/home/x/.rakubrew/versions/moar-blead/install/share/perl6/vendor
    inst#/home/x/.rakubrew/versions/moar-blead/install/share/perl6/core
    ap#
    nqp#
    perl5#
   at SETTING::src/core.c/Exception.pm6:62  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:throw)
 from SETTING::src/core.c/CompUnit/Repository/Perl5.pm6:35  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/NQP.pm6:19  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/AbsolutePath.pm6:8  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/FileSystem.pm6:101  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from gen/moar/World.nqp:1490  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/World.moarvm:load_module)
 from gen/moar/World.nqp:1440  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/World.moarvm:do_pragma_or_load_module)
 from gen/moar/Grammar.nqp:1316  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Grammar.moarvm:statement_control:sym<use>)
 from gen/moar/stage2/QRegex.nqp:1695  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Grammar.moarvm:statement_control)
 from gen/moar/Grammar.nqp:964  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Grammar.moarvm:statement)
 from gen/moar/Grammar.nqp:892  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Grammar.moarvm:statementlist)
 from gen/moar/stage2/NQPHLL.nqp:1464  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:LANG)
 from gen/moar/Grammar.nqp:1344  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Grammar.moarvm:FOREIGN_LANG)
 from gen/moar/Grammar.nqp:840  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Grammar.moarvm:comp_unit)
 from gen/moar/Grammar.nqp:555  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Grammar.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:2258  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:2299  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:2215  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:2250  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:2246  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:2242  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1917  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:2057  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:2112  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:55  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2037  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/rakudo.nqp:128  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/rakudo.nqp:93  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:<entry>)

$ raku --ll-exception -I. -e 'require Foo; say "success";'
Could not find Foo in:
    file#/home/x/data/projects/raku/Inline-Lua-test/foo
    inst#/home/x/.raku
    inst#/home/x/.rakubrew/versions/moar-blead/install/share/perl6/site
    inst#/home/x/.rakubrew/versions/moar-blead/install/share/perl6/vendor
    inst#/home/x/.rakubrew/versions/moar-blead/install/share/perl6/core
    ap#
    nqp#
    perl5#
   at SETTING::src/core.c/Exception.pm6:62  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:throw)
 from SETTING::src/core.c/CompUnit/Repository/Perl5.pm6:35  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/NQP.pm6:19  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/AbsolutePath.pm6:8  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/FileSystem.pm6:101  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from -e:1  (<ephemeral file>:<unit>)
 from -e:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1947  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:2057  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:2112  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:55  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2037  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/rakudo.nqp:128  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/rakudo.nqp:93  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:<entry>)

$ raku --ll-exception -I. -e 'require "Foo.rakumod"; say "success";'
success

$ raku -v
This is Rakudo version 2020.06-65-g90f86d4c9 built on MoarVM version 2020.06-22-gaf5b89b64
implementing Raku 6.d.

$ uname -a
Linux prism 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/debian_version 
bullseye/sid

### PR DESCRIPTION
**Pull request by niner**
…found in CURFS

Fixes #3787

### CODE REVIEW

**Comment by JJ** [comment]
Maybe add a test too?

**Comment by ugexe** [comment]
```
➜  rakudo git:(master) ./install/bin/raku -I file#../zef -e 'use Zef; say 1'
1
```
```
➜  rakudo git:(master) ./install/bin/raku -I file#../zef -e 'use Zefx; say 1'
===SORRY!=== Error while compiling -e
Could not find Zefx in:
    file#/Users/ugexe/repos/rakudo/../zef
    inst#/Users/ugexe/.raku
    inst#/Users/ugexe/repos/rakudo/install/share/perl6/site
    inst#/Users/ugexe/repos/rakudo/install/share/perl6/vendor
    inst#/Users/ugexe/repos/rakudo/install/share/perl6/core
    ap#
    nqp#
    perl5#

Please note that a 'META6.json' file was found in '../zef', of which the 'provides' section was used to determine if a dependency is available or not.  Perhaps you need to add 'Zefx' in the <provides> section of that file?  Or need to specify a directory that does *not* have a 'META6.json' file?
at -e:1
```
```
➜  rakudo git:(master) ./install/bin/raku -I inst#/Users/ugexe/.raku -I file#../zef -e 'use Zefx; say 1'
===SORRY!=== Error while compiling -e
Could not find Zefx in:
    inst#/Users/ugexe/.raku
    file#/Users/ugexe/repos/rakudo/../zef
    inst#/Users/ugexe/repos/rakudo/install/share/perl6/site
    inst#/Users/ugexe/repos/rakudo/install/share/perl6/vendor
    inst#/Users/ugexe/repos/rakudo/install/share/perl6/core
    ap#
    nqp#
    perl5#
at -e:1
```

The above demonstrates this works for the basic case where the missing dependency isn't found in the head `$*REPO` that is a CURFS. It also shows that the message doesn't show up if that same CURFS is not the first repo. Perhaps `$*REPO.grep(CompUnit::Repository::FileSystem).first(*.prefix.add("META6.json").e)` is a better check? Although even then I wonder if the error message itself should report on `s/first/grep/`, since the error could be the result of any of the CURFS repos.

**Comment by ugexe** [comment]
This is an example of the check-all-repos adaptation:
```diff
diff --git a/src/core.c/Exception.pm6 b/src/core.c/Exception.pm6
index e6ae4cf0d..12be3b236 100644
--- a/src/core.c/Exception.pm6
+++ b/src/core.c/Exception.pm6
@@ -3128,8 +3128,8 @@ my class X::CompUnit::UnsatisfiedDependency is Exception {
             and not nqp::istype(nqp::how($ns{$last}), Metamodel::PackageHOW)
     }

-    method !is-missing-from-meta-file() {
-        $*REPO.isa(CompUnit::Repository::FileSystem) and $*REPO.prefix.add("META6.json").e
+    method !missing-from-meta-file() {
+        $*REPO.repo-chain.grep(CompUnit::Repository::FileSystem).grep(*.prefix.add("META6.json").e)
     }

     method message() {
@@ -3141,11 +3141,14 @@ my class X::CompUnit::UnsatisfiedDependency is Exception {
                 ~ ($.specification ~~ / $<name>=.+ '::from' $ /
                     ?? "\n\nIf you meant to use the :from adverb, use"
                         ~ " a single colon for it: $<name>:from<...>\n"
-                    !! self!is-missing-from-meta-file
-                        ?? "\n\nPlease note that a 'META6.json' file was found in '$*REPO.prefix.relative()',"
+                    !! (my $missing := self!missing-from-meta-file)
+                        ?? "\n\nPlease note that a 'META6.json' file was found in the following repositories,"
                             ~ " of which the 'provides' section was used to determine if a dependency is available"
                             ~ " or not.  Perhaps you need to add '$!specification' in the <provides> section of"
-                            ~ " that file?  Or need to specify a directory that does *not* have a 'META6.json' file?"
+                            ~ " one of those files?  Or need to specify a directory that does *not* have a 'META6.json'"
+                            ~ " file?"
+                            ~ "\n"
+                            ~ $missing.map(*.path-spec).join("\n")
                         !! ''
                 )
     }
```

**Comment by lizmat** [comment]
So, is this ready to merge now?

**Comment by JJ** [comment]
> So, is this ready to merge now?

Well, I would still love to have a test, but I'm happy if an issue is opened to create it.

**Pull request merged**
