### PR TITLE
Simplify Kernel signals method using Signal values

### PR DESCRIPTION
**Pull request by jstuder-gh**
The Kernel signals method previously had a lot of logic for determining
signal values on the host system and backends. Now that that logic is
encapsulated into the getsignals ops, this method can be greatly
simplified.

### CODE REVIEW

**Comment by lizmat** [comment]
I assume this should still be merged, correct?

**Comment by jstuder-gh** [comment]
It's been a long time since I've looked at this, but I believe it should still be okay to merge in. All three backends have getsignals working (although I do have an [old PR on NQP repo](https://github.com/perl6/nqp/pull/465) to bring parity between the signals available on WIN32 between the backends).

I know that at least one module in the ecosystem was calling this method (I don't remember what that module was called though), but I don't see how this would break anything.

**Comment by lizmat** [comment]
ok, will merge after the next compiler release, just to be on the safe side

**Comment by jstuder-gh** [comment]
I force-pushed a new version of the branch that is exactly the same as the old version except:

* Rebased on top of current Rakudo master
* Replaced hard-coded ```32``` with value based off ```Signal.enums.values.max```

**Comment by JJ** [comment]
There's a conflict after the change of name. Can you please check?

**Pull request closed without merging**
