### PR TITLE
Speedup ARGFILES read when there is only one input

### PR DESCRIPTION
**Pull request by scovit**
It is common that ARGFILES consists of only one file, such as when working with pipes, this introduces a fast path for that specific condition.

### CODE REVIEW

**Comment by scovit** [comment]
This is the benchmark:
```
$ yes | head -n2000000 | time ./perl6 -e 'my $o = $*OUT; for lines() { $o.say($_) }' > /dev/null
```

**Comment by lizmat** [comment]
What would be against removing the `nqp::isfalse` and reversing the alternatives?

**Comment by scovit** [comment]
I wonder if the fact that this patch is needed does not point to a general slowness and an opportunity for optimisation of `flat`, or if it is not possible to envision an alternative Iterator that concatenate a list of N iterators and optimise in case of N=1..

**Comment by scovit** [comment]
The fix is wrong if we consider why (as far as I understand) there is the need of a `CatHandle` at all, see
#2796

**Comment by JJ** [comment]
First, there are conflicts; second, there does not seem to be a clear need for this, or it's not clear what its effect could be. In the second case, it's probably best to take it over to the problem solving repo. What do you think?

**Comment by scovit** [comment]
Hi JJ. it has been quite awhile. I really don't know if there are still issues.

Could you please run the following benchmarks on Rakudo head?

yes | head -n2000000 | time raku -e 'for lines() {  }' > /dev/null
        2.08 real         2.02 user         0.19 sys
yes | head -n2000000 | time raku -ne ' ' > /dev/null
        3.84 real         4.33 user         0.07 sys
yes | head -n2000000 | time raku -e 'for $*IN.lines() {  }' > /dev/null
        0.72 real         0.67 user         0.09 sys
raku -v
This is Rakudo version 2019.11-506-g06ae7d614 built on MoarVM version 2020.01-17-gefb014f19
implementing Perl 6.d.

**Comment by MasterDuke17** [comment]
FWIW, I just ran those on my system and get identical times for all three.

**Comment by jnthn** [comment]
>

**Comment by scovit** [comment]
This means that the most common usage case has been optimized, good news!

**Comment by scovit** [comment]
@JJ maybe one could open a problem solving issue for the optimization of flat, if it is still as slow as it was before

**Comment by scovit** [comment]
Should the following: 
https://github.com/rakudo/rakudo/issues/2796

also be moved to problem solving?

**Comment by JJ** [comment]
El lun., 4 may. 2020 a las 12:04, Vittore F. Scolari (<
notifications@github.com>) escribió:

> @JJ <https://github.com/JJ> maybe one could open a problem solving issue
> for the optimization of flat, if it is still as slow as it was before
>
Please do that. I'm not aware of all the context.

**Comment by jnthn** [comment]
Almost certainly was handled by the changes I did in response to #3545.

**Pull request closed without merging**
