### PR TITLE
RakuAST: add Dutch in foreign language deparsing

### PR DESCRIPTION
**Pull request by lizmat**
I *think* we should have officially supported foreign language translations in core, to ensure that we don't get into a Babylonian knot of language misunderstandings.

OTOH, this could also well live in the ecosystem, to allow updates regardless of Rakudo / Raku language versions.

### CODE REVIEW

**Comment by JJ** [comment]
Just a suggestion here. To make implementation easier, could the name of the file/role be one of the standard codes for language? As in NL in this case. That would make easier to map locale settings to these deparsers.

**Comment by lizmat** [comment]
Aahh... good point!   Which standard should we use for that?  I guess ISO-639?

**Comment by JJ** [comment]
> Aahh... good point! Which standard should we use for that? I guess ISO-639?

That seems to be the one used for locale settings, so I guess so.

**Comment by vrurg** [comment]
To be honest, I wouldn't get the module's purpose from its name as NL may stand for too many things. Shouldn't it be `RakuAST::Deparse::L10N::NL`?

**Comment by lizmat** [comment]
@vrurg I think it being a subclass of `::Deparse` already gives that away.

**Comment by ugexe** [comment]
> @vrurg I think it being a subclass of ::Deparse already gives that away.

I don't think so. When I read something like `::Deparse::IO` I don't immediately assume its referencing [some language](https://en.wikipedia.org/wiki/Ido)

**Pull request merged**
