### PR TITLE
Clean up sockets created by IO::Socket::INET.new on error

### PR DESCRIPTION
**Pull request by Kaiepi**
Related to #4370.

### CODE REVIEW

**Review by lizmat — APPROVED** [review]

**Review by lizmat — APPROVED** [review]

**Comment by Zer0-Tolerance** [comment]
Hi , any idea when this will be merged ?

**Comment by vrurg** [comment]
@Kaiepi any reason for this to wait?

**Comment by Kaiepi** [comment]
I need to double check that the JVM copes with this OK. Past that, no.

**Comment by Kaiepi** [comment]
Good to go.

**Comment by vrurg** [comment]
@Kaiepi thank you!

**Comment by Zer0-Tolerance** [comment]
hi all, 
Just check the behavior in 2021.07 and Raku is still not closing connection after timeout. Can you confirm on your side ? Pretty annoying because it's seems to prevent any kind of TCP Scan of more than 16k IP adresses.

**Comment by Kaiepi** [comment]
@Zer0-Tolerance Are they synchronous sockets? `IO::Socket::INET`'s sockets are getting closed on timeout for me locally, but I'm on an OpenBSD system, and don't have an OS X one to test with offhand.

**Comment by lizmat** [comment]
Is there a golf that I can use to check on MacOS ?

**Comment by Kaiepi** [comment]
I can't write a straight golf for this, but OS X should be BSD-ish enough for the strategy I used locally to apply:
1. Run:
```raku
shell "ktrace -p $*PID";
say try { IO::Socket::INET.connect: '127.0.0.1', 12345 } // $!;
sleep;
```
2. An error should pop up eventually, and should be `ETIMEOUT`-related. If not, `docs.raku.org` seems apt to time out on the same port.
3. In the same directory, run:
```sh
$ kdump | less
```
4. There may or may not be multiple `socket(2)` calls depending on the host. `IO::Socket::INET`'s socket should be the last of these, followed closely by a `connect(2)` call. Note the address given and see if a call to `close(2)` for this socket appears at any point afterwards, in which case don't end the script yet.
5. If closed, `$ netstat -p tcp` should not include any sockets with the connection's address.

**Comment by lizmat** [comment]
````
$ ktrace -p 7987
ktrace: unknown command `-p'
usage:	ktrace info
	ktrace trace [-AnNrsStu] [--remotetime] [-T <timeout>] [-f <filter-desc>] [-b <buffer-size-mb>] [-R <raw file> | -E]  [-C <code file> [...]] [-x <process name|pid> [...] | -p <process name|pid> [...]] [-F] [-c <command> [...]]
	ktrace dump [-E] [-l <compression-level>] [-T <timeout>] [-f <filter-desc>] [-b <buffer-size-mb>] [-p <pid-or-process-name>] [<path>] [-c <command> [...]]
	ktrace init -b <buffer-size-mb> | -n <n-events>
	ktrace setopt [-x <pid-or-process-name> | -p <pid-or-process-name>] [-w] [-f <filter-desc>]
	ktrace enable
	ktrace disable
	ktrace decode <debugid> [<debugid> ...]
	ktrace remove
	ktrace reset
	ktrace emit <debugid> [<arg1> [<arg2> [<arg3> [<arg4>]]]]
	ktrace symbolicate <path>
	ktrace stacks [-R <raw file> | -E]  [-C <code file> [...]] [-x <process name|pid> [...] | -p <process name|pid> [...]] [-F]
	ktrace compress [-l fast|balanced|small] <path>
		fast: fast speed, small compression ratio
		balanced: balanced speed and compression ratio
		small: slow speed, high compression ratio (default)
	ktrace artrace [-nr] [-t <time>] [-i <interval>] [-o <filename>] [-b <buffer-size-mb>] [-f <filter-desc>] [-F <filter-desc>] [-p <pid-or-process-name>] [--remote[=<remote-device>]] [--type=full|profile|lite|morelite] [--kperf <sample-desc>] [-c <command> [...]]

	-R <raw file> : read events from the trace file at path <raw file>
	-E : use the existing trace session, instead of setting up a new one
	-C <code file> : provide codes files that name the events
	-x <process name|pid> : ignore the events from processes specified
	-p <process name|pid> : show only events from processes specified
	-F : print the filter description used to configure ktrace
````

**Comment by Zer0-Tolerance** [comment]
> @Zer0-Tolerance Are they synchronous sockets? `IO::Socket::INET`'s sockets are getting closed on timeout for me locally, but I'm on an OpenBSD system, and don't have an OS X one to test with offhand.

Yes async socket from IO::Socket::Async::SSL

**Pull request merged**
