### PR TITLE
Work on 6.e PseudoStash clarification

### PR DESCRIPTION
**Pull request by vrurg**
This is a solution approach for Raku/problem-solving#294.

### CODE REVIEW

**Comment by vrurg** [comment]
Basically ready for merge after a review and Raku/roast#755 is ready and finalized.

**Comment by vrurg** [comment]
Returned into draft as I hope to implemented extended support for static chains mapping into `OUR`, and dynamics into `$*PROMSE!dynamic_context`, `GLOBAL`, and `PROCESS`.

**Comment by vrurg** [comment]
I'm basically done with this one. Wonder what makes JVM failing, but this is to be taken care of later.

**Comment by vrurg** [comment]
Ready for merge.

**Comment by vrurg** [comment]
Anybody minds merging this?

**Comment by 2colours** [comment]
Well, it should be updated again... but will @jnthn review it in the foreseeable future?

**Pull request merged**
