### PR TITLE
Make Cursor's $!name a str and speed up Cursor.MATCH() by 10-15%

### PR DESCRIPTION
**Pull request by MasterDuke17**
Hopefully turning into a native will be more efficient.

Passes `make m-spectest`

Requires https://github.com/perl6/nqp/pull/334

### CODE REVIEW

**Comment by lizmat** [comment]
If this about making things faster, what about converting:

!nqp::isnull_s($name) && nqp::defined($name) && $name ne '' {

to

nqp::not_i(nqp::isnull_s($name)) && nqp::isgt_i(nqp::chars($name),0) {

and similar things involving == with native ints ?

**Comment by MasterDuke17** [comment]
@lizmat I was originally only hoping to make the NQP MATCH() faster, but this one is now measurably faster.

**Comment by lizmat** [comment]
make install fails with:

/Users/liz/Github/rakudo.moar/install/bin/moar --libpath="/Users/liz/Github/rakudo.moar/install/share/nqp/lib" --libpath="/Users/liz/Github/rakudo.moar/install/share/nqp/lib" perl6.moarvm --nqp-lib=blib tools/build/create-moar-runner.pl "/Users/liz/Github/rakudo.moar/install/bin/moar" perl6.moarvm perl6-m . "" --nqp-lib=blib "/Users/liz/Github/rakudo.moar/install/share/nqp/lib" "/Users/liz/Github/rakudo.moar/install/share/nqp/lib" .
P6opaque: invalid native access attribute '$!name' in type Cursor for kind str
  in block <unit> at tools/build/create-moar-runner.pl line 10

**Comment by MasterDuke17** [comment]
Did you merge and build the NQP PR (https://github.com/perl6/nqp/pull/334) first?

**Pull request merged**
